// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AcceptContactSuggestionAcceptContactSuggestionResponse struct {
	Data json.RawMessage `json:"data"`
}

type AcceptContactSuggestionRequest struct {
	AcceptedById string `json:"acceptedById"`
	RoleKey      string `json:"roleKey"`
	Version      int    `json:"version"`
}

type ActivityEvent struct {
	ActorId       string          `json:"actorId"`
	ActorType     string          `json:"actorType"`
	Id            string          `json:"id"`
	Metadata      json.RawMessage `json:"metadata"`
	Payload       json.RawMessage `json:"payload"`
	Timestamp     string          `json:"timestamp"`
	TransactionId string          `json:"transactionId"`
	Type          string          `json:"type"`
}

type Address struct {
	City        string `json:"city"`
	ClosingDate string `json:"closingDate"`
	County      string `json:"county"`
	State       string `json:"state"`
	Street      string `json:"street"`
	Unit        string `json:"unit"`
	Zip         string `json:"zip"`
}

type AddressEnrichResponse struct {
	Data string          `json:"data"`
	Meta json.RawMessage `json:"meta"`
}

type AddressSuggestion struct {
	City   string `json:"city"`
	Id     string `json:"id"`
	Label  string `json:"label"`
	State  string `json:"state"`
	Street string `json:"street"`
	Unit   string `json:"unit"`
	Zip    string `json:"zip"`
}

type AdminDismissDlqentryResponse struct {
	Data json.RawMessage `json:"data"`
}

type AdminGetApprovalRateResponse struct {
	Data json.RawMessage `json:"data"`
}

type AdminGetPortalAdoptionResponse struct {
	Data json.RawMessage `json:"data"`
}

type AdminGetWeeklySummaryResponse struct {
	Data json.RawMessage `json:"data"`
}

type AdminRetryDlqentryResponse struct {
	Data json.RawMessage `json:"data"`
}

type AgentAction struct {
	ApprovedAt       string          `json:"approvedAt"`
	ApprovedById     string          `json:"approvedById"`
	CreatedAt        string          `json:"createdAt"`
	Id               string          `json:"id"`
	IdempotencyKey   string          `json:"idempotencyKey"`
	Payload          json.RawMessage `json:"payload"`
	Reasoning        string          `json:"reasoning"`
	ResumeToken      string          `json:"resumeToken"`
	SourceDocumentId string          `json:"sourceDocumentId"`
	SourcePage       int             `json:"sourcePage"`
	SourceQuote      string          `json:"sourceQuote"`
	StaleReason      string          `json:"staleReason"`
	Status           string          `json:"status"`
	TransactionId    string          `json:"transactionId"`
	Type             string          `json:"type"`
	Version          int             `json:"version"`
	WorkflowRunId    string          `json:"workflowRunId"`
}

type AgentActionsCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type AgentActionsInvalidateStaleActionsResponse struct {
	Data json.RawMessage `json:"data"`
}

type AgentToken struct {
	CreatedAt       string          `json:"createdAt"`
	ExpiresAt       string          `json:"expiresAt"`
	Id              string          `json:"id"`
	LastUsedAt      string          `json:"lastUsedAt"`
	Name            string          `json:"name"`
	Permission      string          `json:"permission"`
	RevokedAt       string          `json:"revokedAt"`
	RotatedFromId   string          `json:"rotatedFromId"`
	Scope           string          `json:"scope"`
	ScopeResourceId string          `json:"scopeResourceId"`
	TokenPrefix     string          `json:"tokenPrefix"`
	UpdatedAt       string          `json:"updatedAt"`
	Usage           json.RawMessage `json:"usage"`
}

type AgentTokenUsageEntry struct {
	Endpoint   string `json:"endpoint"`
	Id         string `json:"id"`
	Method     string `json:"method"`
	StatusCode int    `json:"statusCode"`
	Timestamp  string `json:"timestamp"`
}

type AgentTokenUsageSummary struct {
	LastRequest json.RawMessage `json:"lastRequest"`
	UsageCount  int             `json:"usageCount"`
}

type AgentTokensCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type ApplyTemplateResponse struct {
	Data json.RawMessage `json:"data"`
}

type ApprovalMetrics struct {
	ApprovalRate        float64 `json:"approvalRate"`
	ApprovedWithEdit    int     `json:"approvedWithEdit"`
	ApprovedWithoutEdit int     `json:"approvedWithoutEdit"`
	Rejected            int     `json:"rejected"`
	TcUserId            string  `json:"tcUserId"`
	TotalActions        int     `json:"totalActions"`
	TransactionId       string  `json:"transactionId"`
	TrustAlert          bool    `json:"trustAlert"`
}

type ApprovalRequest struct {
	ApprovedById string `json:"approvedById"`
	Version      int    `json:"version"`
}

type ApproveAgentActionResponse struct {
	Data json.RawMessage `json:"data"`
}

type ApproveConnectorActionProposal struct {
	ApprovedById   string `json:"approvedById"`
	IdempotencyKey string `json:"idempotencyKey"`
	Version        int    `json:"version"`
}

type BatchWriteFields struct {
	Fields         json.RawMessage `json:"fields"`
	IdempotencyKey string          `json:"idempotencyKey"`
}

type BillingCheckoutRequest struct {
	CancelUrl  string `json:"cancelUrl"`
	PlanId     string `json:"planId"`
	SuccessUrl string `json:"successUrl"`
	TcId       string `json:"tcId"`
}

type BillingCreateCheckoutSessionResponse struct {
	Data json.RawMessage `json:"data"`
}

type BillingCreatePortalSessionResponse struct {
	Data json.RawMessage `json:"data"`
}

type BillingGetSummaryResponse struct {
	Data json.RawMessage `json:"data"`
}

type BillingHandleStripeWebhookResponse struct {
	Received bool `json:"received"`
}

type BillingInvoice struct {
	AmountDueCents   int    `json:"amountDueCents"`
	AmountPaidCents  int    `json:"amountPaidCents"`
	CreatedAt        string `json:"createdAt"`
	Currency         string `json:"currency"`
	HostedInvoiceUrl string `json:"hostedInvoiceUrl"`
	Id               string `json:"id"`
	InvoicePdfUrl    string `json:"invoicePdfUrl"`
	Status           string `json:"status"`
}

type BillingPortalRequest struct {
	ReturnUrl string `json:"returnUrl"`
	TcId      string `json:"tcId"`
}

type BillingSummary struct {
	CanCreateTransaction bool            `json:"canCreateTransaction"`
	CancelAtPeriodEnd    bool            `json:"cancelAtPeriodEnd"`
	CurrentPeriodEndsAt  string          `json:"currentPeriodEndsAt"`
	FreeTierLimit        int             `json:"freeTierLimit"`
	FreeTierRemaining    int             `json:"freeTierRemaining"`
	GracePeriodEndsAt    string          `json:"gracePeriodEndsAt"`
	Invoices             json.RawMessage `json:"invoices"`
	PaywallCode          string          `json:"paywallCode"`
	PaywallMessage       string          `json:"paywallMessage"`
	PlanId               string          `json:"planId"`
	Plans                json.RawMessage `json:"plans"`
	SeatLimit            int             `json:"seatLimit"`
	SeatsUsed            int             `json:"seatsUsed"`
	StripeConfigured     bool            `json:"stripeConfigured"`
	SubscriptionStatus   string          `json:"subscriptionStatus"`
	TcId                 string          `json:"tcId"`
	TransactionsCreated  int             `json:"transactionsCreated"`
	TrialEndsAt          string          `json:"trialEndsAt"`
}

type CalloutsCheckSeenResponse struct {
	Data json.RawMessage `json:"data"`
}

type CalloutsMarkSeenResponse struct {
	Data json.RawMessage `json:"data"`
}

type CancelIntakeSessionResponse struct {
	Data json.RawMessage `json:"data"`
}

type CapturedEmailAttachment struct {
	Classification json.RawMessage `json:"classification"`
	CreatedAt      string          `json:"createdAt"`
	FileSize       int             `json:"fileSize"`
	Id             string          `json:"id"`
	MimeType       string          `json:"mimeType"`
	Title          string          `json:"title"`
	UpdatedAt      string          `json:"updatedAt"`
}

type CapturedEmailClassification struct {
	ClassifiedAt   string  `json:"classifiedAt"`
	Confidence     float64 `json:"confidence"`
	DocType        string  `json:"docType"`
	OneLineSummary string  `json:"oneLineSummary"`
	OverriddenAt   string  `json:"overriddenAt"`
	UrgencyFlag    bool    `json:"urgencyFlag"`
}

type CapturedEmailEntry struct {
	AttachmentCount int             `json:"attachmentCount"`
	Attachments     json.RawMessage `json:"attachments"`
	Body            string          `json:"body"`
	DocType         string          `json:"docType"`
	EmailId         string          `json:"emailId"`
	Sender          string          `json:"sender"`
	Subject         string          `json:"subject"`
	Summary         string          `json:"summary"`
	Timestamp       string          `json:"timestamp"`
	UrgencyFlag     bool            `json:"urgencyFlag"`
}

type CloseDeveloperHealthGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type CloseDeveloperProfileGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type CloseDeveloperProfilePatchResponse struct {
	Data json.RawMessage `json:"data"`
}

type CommitIntakeSessionResponse struct {
	Data json.RawMessage `json:"data"`
}

type ConfirmFilterInstallationResponse struct {
	FilterInstalled   bool   `json:"filterInstalled"`
	FilterInstalledAt string `json:"filterInstalledAt"`
}

type ConnectorActionProposal struct {
	ApprovalIdempotencyKey string          `json:"approvalIdempotencyKey"`
	ApprovedAt             string          `json:"approvedAt"`
	ApprovedById           string          `json:"approvedById"`
	AuditEventIds          json.RawMessage `json:"auditEventIds"`
	CapabilityId           string          `json:"capabilityId"`
	ConnectorId            string          `json:"connectorId"`
	CreatedAt              string          `json:"createdAt"`
	DryRunResult           json.RawMessage `json:"dryRunResult"`
	ExecutedAt             string          `json:"executedAt"`
	ExecutedById           string          `json:"executedById"`
	ExecutedByType         string          `json:"executedByType"`
	ExecutionResult        json.RawMessage `json:"executionResult"`
	FailureReason          string          `json:"failureReason"`
	Id                     string          `json:"id"`
	IdempotencyKey         string          `json:"idempotencyKey"`
	InputSummary           json.RawMessage `json:"inputSummary"`
	ProposedById           string          `json:"proposedById"`
	ProposedByType         string          `json:"proposedByType"`
	Purpose                string          `json:"purpose"`
	Status                 string          `json:"status"`
	TaskId                 string          `json:"taskId"`
	TransactionId          string          `json:"transactionId"`
	UpdatedAt              string          `json:"updatedAt"`
	Version                int             `json:"version"`
}

type ConnectorActionRun struct {
	ActorId        string          `json:"actorId"`
	ActorType      string          `json:"actorType"`
	AuditEventId   string          `json:"auditEventId"`
	CompletedAt    string          `json:"completedAt"`
	CreatedAt      string          `json:"createdAt"`
	ErrorMessage   string          `json:"errorMessage"`
	Id             string          `json:"id"`
	IdempotencyKey string          `json:"idempotencyKey"`
	Phase          string          `json:"phase"`
	ProposalId     string          `json:"proposalId"`
	Result         json.RawMessage `json:"result"`
	Status         string          `json:"status"`
	TransactionId  string          `json:"transactionId"`
}

type ConnectorActionsApproveProposalResponse struct {
	Data json.RawMessage `json:"data"`
}

type ConnectorActionsCreateProposalResponse struct {
	Data json.RawMessage `json:"data"`
	Runs json.RawMessage `json:"runs"`
}

type ConnectorActionsDryRunResponse struct {
	Data json.RawMessage `json:"data"`
	Run  json.RawMessage `json:"run"`
}

type ConnectorActionsExecuteResponse struct {
	Data json.RawMessage `json:"data"`
	Run  json.RawMessage `json:"run"`
}

type ConnectorActionsGetProposalResponse struct {
	Data json.RawMessage `json:"data"`
	Runs json.RawMessage `json:"runs"`
}

type Contact struct {
	Address            json.RawMessage `json:"address"`
	AgentLicenseNumber string          `json:"agentLicenseNumber"`
	Anniversary        string          `json:"anniversary"`
	Birthday           string          `json:"birthday"`
	CreatedAt          string          `json:"createdAt"`
	CreatedBy          string          `json:"createdBy"`
	Emails             json.RawMessage `json:"emails"`
	Fax                string          `json:"fax"`
	FirstName          string          `json:"firstName"`
	Groups             json.RawMessage `json:"groups"`
	Id                 string          `json:"id"`
	LastName           string          `json:"lastName"`
	LeadSource         string          `json:"leadSource"`
	NickName           string          `json:"nickName"`
	Office             json.RawMessage `json:"office"`
	Phones             json.RawMessage `json:"phones"`
	Prefix             string          `json:"prefix"`
	Suffix             string          `json:"suffix"`
	Tags               json.RawMessage `json:"tags"`
	UpdatedAt          string          `json:"updatedAt"`
	Website            string          `json:"website"`
}

type ContactsCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type ContactsDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type ContactsGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type ContactsLinkToTransactionResponse struct {
	Data json.RawMessage `json:"data"`
}

type ContactsUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type ContractUploadResponse struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CreateActivityEvent struct {
	ActorId   string          `json:"actorId"`
	ActorType string          `json:"actorType"`
	Metadata  json.RawMessage `json:"metadata"`
	Payload   json.RawMessage `json:"payload"`
	Type      string          `json:"type"`
}

type CreateAgentAction struct {
	IdempotencyKey   string          `json:"idempotencyKey"`
	Payload          json.RawMessage `json:"payload"`
	Reasoning        string          `json:"reasoning"`
	ResumeToken      string          `json:"resumeToken"`
	SourceDocumentId string          `json:"sourceDocumentId"`
	SourcePage       int             `json:"sourcePage"`
	SourceQuote      string          `json:"sourceQuote"`
	TransactionId    string          `json:"transactionId"`
	Type             string          `json:"type"`
	WorkflowRunId    string          `json:"workflowRunId"`
}

type CreateAgentTokenRequest struct {
	ExpiresAt       string `json:"expiresAt"`
	Name            string `json:"name"`
	Permission      string `json:"permission"`
	Scope           string `json:"scope"`
	ScopeResourceId string `json:"scopeResourceId"`
}

type CreateConnectorActionProposal struct {
	ActionInput    json.RawMessage `json:"actionInput"`
	CapabilityId   string          `json:"capabilityId"`
	ConnectorId    string          `json:"connectorId"`
	IdempotencyKey string          `json:"idempotencyKey"`
	Purpose        string          `json:"purpose"`
	TaskId         string          `json:"taskId"`
	TransactionId  string          `json:"transactionId"`
}

type CreateContact struct {
	Address            json.RawMessage `json:"address"`
	AgentLicenseNumber string          `json:"agentLicenseNumber"`
	Emails             json.RawMessage `json:"emails"`
	Fax                string          `json:"fax"`
	FirstName          string          `json:"firstName"`
	Groups             json.RawMessage `json:"groups"`
	LastName           string          `json:"lastName"`
	LeadSource         string          `json:"leadSource"`
	NickName           string          `json:"nickName"`
	Office             json.RawMessage `json:"office"`
	Phones             json.RawMessage `json:"phones"`
	Prefix             string          `json:"prefix"`
	Suffix             string          `json:"suffix"`
	Tags               json.RawMessage `json:"tags"`
	Website            string          `json:"website"`
}

type CreateDeal struct {
	Address        json.RawMessage `json:"address"`
	Agent          json.RawMessage `json:"agent"`
	AssignedTo     json.RawMessage `json:"assignedTo"`
	Client         json.RawMessage `json:"client"`
	DateFields     json.RawMessage `json:"dateFields"`
	SourceIntakeId string          `json:"sourceIntakeId"`
	Type           string          `json:"type"`
}

type CreateDealDateFields struct {
	ClosingDate               string `json:"closing_date"`
	LeaseEndDate              string `json:"lease_end_date"`
	LeaseStartDate            string `json:"lease_start_date"`
	ListingAgreementStartDate string `json:"listing_agreement_start_date"`
}

type CreateDealResponse struct {
	Address              json.RawMessage `json:"address"`
	AgentContext         json.RawMessage `json:"agentContext"`
	AssignedTo           json.RawMessage `json:"assignedTo"`
	CreatedAt            string          `json:"createdAt"`
	CreatedBy            string          `json:"createdBy"`
	FilterXmlDownloadUrl string          `json:"filterXmlDownloadUrl"`
	Id                   string          `json:"id"`
	InboundEmailAddress  string          `json:"inboundEmailAddress"`
	MagicAddress         string          `json:"magicAddress"`
	Status               string          `json:"status"`
	TeamId               string          `json:"teamId"`
	Type                 string          `json:"type"`
	UpdatedAt            string          `json:"updatedAt"`
}

type CreateForm struct {
	Fields json.RawMessage `json:"fields"`
	Name   string          `json:"name"`
	TcId   string          `json:"tcId"`
}

type CreatePortalInvite struct {
	ContactId string `json:"contactId"`
	Email     string `json:"email"`
	RoleKey   string `json:"roleKey"`
}

type CreateTask struct {
	AssignedRoles        json.RawMessage `json:"assignedRoles"`
	AssigneeContactId    string          `json:"assigneeContactId"`
	AssigneeId           string          `json:"assigneeId"`
	AssigneeTcId         string          `json:"assigneeTcId"`
	AssigneeType         string          `json:"assigneeType"`
	DateRule             json.RawMessage `json:"dateRule"`
	Dependencies         json.RawMessage `json:"dependencies"`
	Description          string          `json:"description"`
	DueDate              string          `json:"dueDate"`
	LockCondition        json.RawMessage `json:"lockCondition"`
	PortalVisible        bool            `json:"portalVisible"`
	Slug                 string          `json:"slug"`
	SourceCatalogId      string          `json:"sourceCatalogId"`
	SourceCatalogVersion int             `json:"sourceCatalogVersion"`
	SubTasks             json.RawMessage `json:"subTasks"`
	Tags                 json.RawMessage `json:"tags"`
	Title                string          `json:"title"`
}

type CreateTemplate struct {
	Data        string `json:"data"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Type        string `json:"type"`
}

type DLQEntry struct {
	Attempts      int             `json:"attempts"`
	ErrorMessage  string          `json:"errorMessage"`
	ErrorStack    string          `json:"errorStack"`
	FailedAt      string          `json:"failedAt"`
	Id            string          `json:"id"`
	JobData       json.RawMessage `json:"jobData"`
	JobId         string          `json:"jobId"`
	QueueName     string          `json:"queueName"`
	TransactionId string          `json:"transactionId"`
}

type Deal struct {
	Address             json.RawMessage `json:"address"`
	AgentContext        json.RawMessage `json:"agentContext"`
	AssignedTo          json.RawMessage `json:"assignedTo"`
	CreatedAt           string          `json:"createdAt"`
	CreatedBy           string          `json:"createdBy"`
	Id                  string          `json:"id"`
	InboundEmailAddress string          `json:"inboundEmailAddress"`
	Status              string          `json:"status"`
	TeamId              string          `json:"teamId"`
	Type                string          `json:"type"`
	UpdatedAt           string          `json:"updatedAt"`
}

type DealListItem struct {
	Address             json.RawMessage `json:"address"`
	AgentContext        json.RawMessage `json:"agentContext"`
	AssignedTo          json.RawMessage `json:"assignedTo"`
	CreatedAt           string          `json:"createdAt"`
	CreatedBy           string          `json:"createdBy"`
	Health              string          `json:"health"`
	Id                  string          `json:"id"`
	InboundEmailAddress string          `json:"inboundEmailAddress"`
	Status              string          `json:"status"`
	TeamId              string          `json:"teamId"`
	Type                string          `json:"type"`
	UpdatedAt           string          `json:"updatedAt"`
}

type DismissContactSuggestionDismissContactSuggestionResponse struct {
	Data json.RawMessage `json:"data"`
}

type DismissContactSuggestionRequest struct {
	DismissedById string `json:"dismissedById"`
	Version       int    `json:"version"`
}

type Document struct {
	Category           string          `json:"category"`
	CreatedAt          string          `json:"createdAt"`
	CurrentVersionId   string          `json:"currentVersionId"`
	DeletedAt          string          `json:"deletedAt"`
	FileRoleKey        string          `json:"fileRoleKey"`
	FileSize           int             `json:"fileSize"`
	FileUrl            string          `json:"fileUrl"`
	Id                 string          `json:"id"`
	Metadata           json.RawMessage `json:"metadata"`
	MimeType           string          `json:"mimeType"`
	RequiredForClosing bool            `json:"requiredForClosing"`
	RoleAccess         json.RawMessage `json:"roleAccess"`
	Status             string          `json:"status"`
	Title              string          `json:"title"`
	TransactionId      string          `json:"transactionId"`
	UpdatedAt          string          `json:"updatedAt"`
	UploadedAt         string          `json:"uploadedAt"`
}

type DocumentClassification struct {
	DocType        string `json:"docType"`
	OneLineSummary string `json:"oneLineSummary"`
	UrgencyFlag    bool   `json:"urgencyFlag"`
}

type DocumentVersion struct {
	DocumentId    string `json:"documentId"`
	FileSize      int    `json:"fileSize"`
	Id            string `json:"id"`
	MimeType      string `json:"mimeType"`
	StorageKey    string `json:"storageKey"`
	SupersededAt  string `json:"supersededAt"`
	UploadedAt    string `json:"uploadedAt"`
	UploadedBy    string `json:"uploadedBy"`
	VersionNumber int    `json:"versionNumber"`
}

type DocumentsGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type DocumentsLinkResponse struct {
	Data json.RawMessage `json:"data"`
}

type DocumentsSoftDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type DocumentsUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type DocumentsUploadResponse struct {
	Data json.RawMessage `json:"data"`
}

type DownloadDocumentResponse struct {
	Data json.RawMessage `json:"data"`
}

type DraftEmailRequest struct {
	CustomInstructions string `json:"customInstructions"`
	EmailType          string `json:"emailType"`
	RecipientPartyRole string `json:"recipientPartyRole"`
}

type DryRunConnectorAction struct {
	IdempotencyKey string `json:"idempotencyKey"`
}

type Email struct {
	AgentReasoning   string          `json:"agentReasoning"`
	AttachmentIds    json.RawMessage `json:"attachmentIds"`
	BccAddresses     json.RawMessage `json:"bccAddresses"`
	BodyHtml         string          `json:"bodyHtml"`
	CcAddresses      json.RawMessage `json:"ccAddresses"`
	CreatedAt        string          `json:"createdAt"`
	Direction        string          `json:"direction"`
	EditedBodyHtml   string          `json:"editedBodyHtml"`
	EditedSubject    string          `json:"editedSubject"`
	EmailType        string          `json:"emailType"`
	FromAddress      string          `json:"fromAddress"`
	Id               string          `json:"id"`
	InReplyTo        string          `json:"inReplyTo"`
	MessageId        string          `json:"messageId"`
	OriginalBodyHtml string          `json:"originalBodyHtml"`
	OriginalSubject  string          `json:"originalSubject"`
	Status           string          `json:"status"`
	Subject          string          `json:"subject"`
	ThreadId         string          `json:"threadId"`
	ToAddress        string          `json:"toAddress"`
	ToPartyRole      string          `json:"toPartyRole"`
	TransactionId    string          `json:"transactionId"`
	UpdatedAt        string          `json:"updatedAt"`
}

type EmailFilterConfirmTransactionInstallationResponse struct {
	Data json.RawMessage `json:"data"`
}

type EmailFilterGetTransactionResponse struct {
	Data json.RawMessage `json:"data"`
}

type EmailsDraftResponse struct {
	Data json.RawMessage `json:"data"`
}

type EmailsUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type EmptyFilterResponse struct {
	Emails  json.RawMessage `json:"emails"`
	Message string          `json:"message"`
}

type EventsCreateActivityResponse struct {
	Data json.RawMessage `json:"data"`
}

type ExchangeTokenRequest struct {
	Token string `json:"token"`
}

type ExecuteConnectorAction struct {
	IdempotencyKey string `json:"idempotencyKey"`
	Version        int    `json:"version"`
}

type ExtractionCorrection struct {
	Confidence       float64 `json:"confidence"`
	CorrectedAt      string  `json:"correctedAt"`
	CorrectedBy      string  `json:"correctedBy"`
	CorrectedValue   string  `json:"correctedValue"`
	FieldKey         string  `json:"fieldKey"`
	Id               string  `json:"id"`
	Model            string  `json:"model"`
	OriginalAIValue  string  `json:"originalAIValue"`
	PromptVersion    string  `json:"promptVersion"`
	SourceDocumentId string  `json:"sourceDocumentId"`
	TransactionId    string  `json:"transactionId"`
}

type FieldAccuracy struct {
	AccuracyRate         float64 `json:"accuracyRate"`
	Corrections          int     `json:"corrections"`
	FieldKey             string  `json:"fieldKey"`
	MostRecentCorrection string  `json:"mostRecentCorrection"`
	TotalExtractions     int     `json:"totalExtractions"`
}

type FieldDefinition struct {
	AgentDescription string          `json:"agentDescription"`
	Config           json.RawMessage `json:"config"`
	Group            string          `json:"group"`
	Id               string          `json:"id"`
	Key              string          `json:"key"`
	Label            string          `json:"label"`
	MergeKey         string          `json:"mergeKey"`
	PortalVisible    bool            `json:"portalVisible"`
	Required         bool            `json:"required"`
	RequiredByStatus json.RawMessage `json:"requiredByStatus"`
	Section          string          `json:"section"`
	Type             string          `json:"type"`
}

type FieldValue struct {
	AiValue          string  `json:"aiValue"`
	Confidence       float64 `json:"confidence"`
	DisputeReason    string  `json:"disputeReason"`
	FieldKey         string  `json:"fieldKey"`
	ReviewState      string  `json:"reviewState"`
	Reviewed         bool    `json:"reviewed"`
	Source           string  `json:"source"`
	SourceDocumentId string  `json:"sourceDocumentId"`
	SourcePage       int     `json:"sourcePage"`
	SourceQuote      string  `json:"sourceQuote"`
	StaleReason      string  `json:"staleReason"`
	TcValue          string  `json:"tcValue"`
	Value            string  `json:"value"`
	Version          int     `json:"version"`
}

type FieldsBatchWriteResponse struct {
	Data json.RawMessage `json:"data"`
}

type FieldsMarkDisputedResponse struct {
	Data json.RawMessage `json:"data"`
}

type FieldsMarkReviewedResponse struct {
	Data json.RawMessage `json:"data"`
}

type FieldsMarkStaleResponse struct {
	Data json.RawMessage `json:"data"`
}

type FieldsReviewSummaryResponse struct {
	Data json.RawMessage `json:"data"`
}

type FieldsSetValueResponse struct {
	Data json.RawMessage `json:"data"`
}

type Form struct {
	CreatedAt     string          `json:"createdAt"`
	Fields        json.RawMessage `json:"fields"`
	Id            string          `json:"id"`
	Name          string          `json:"name"`
	PublicUrlSlug string          `json:"publicUrlSlug"`
	TcId          string          `json:"tcId"`
	UpdatedAt     string          `json:"updatedAt"`
}

type FormSubmission struct {
	CreatedAt     string          `json:"createdAt"`
	FormId        string          `json:"formId"`
	Id            string          `json:"id"`
	SubmittedBy   string          `json:"submittedBy"`
	TransactionId string          `json:"transactionId"`
	Values        json.RawMessage `json:"values"`
}

type FormsCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type FormsDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type FormsGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type FormsUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type IgnoredInboundEmail struct {
	Accepted  bool   `json:"accepted"`
	Reason    string `json:"reason"`
	Recipient string `json:"recipient"`
}

type InboundEmail struct {
	From      string `json:"from"`
	Html      string `json:"html"`
	InReplyTo string `json:"inReplyTo"`
	MessageId string `json:"messageId"`
	Subject   string `json:"subject"`
	Text      string `json:"text"`
	To        string `json:"to"`
}

type IntakeCommitResponse struct {
	DocumentId    string `json:"documentId"`
	TransactionId string `json:"transactionId"`
}

type IntakeGetSessionResponse struct {
	Data json.RawMessage `json:"data"`
}

type IntakeSessionResponse struct {
	ExtractedPayload json.RawMessage `json:"extractedPayload"`
	ExtractionError  string          `json:"extractionError"`
	Id               string          `json:"id"`
	Status           string          `json:"status"`
}

type IntakeUndoAutoCreatedTransactionResponse struct {
	Data json.RawMessage `json:"data"`
}

type IntakeUndoResponse struct {
	IntakeId      string `json:"intakeId"`
	Status        string `json:"status"`
	TransactionId string `json:"transactionId"`
}

type IntakeUploadContractForResponse struct {
	Data json.RawMessage `json:"data"`
}

type InvalidateStaleRequest struct {
	FieldKey      string `json:"fieldKey"`
	TaskTitle     string `json:"taskTitle"`
	TransactionId string `json:"transactionId"`
	Trigger       string `json:"trigger"`
}

type LinkContact struct {
	Address                  json.RawMessage `json:"address"`
	AgentLicenseNumber       string          `json:"agentLicenseNumber"`
	ContactId                string          `json:"contactId"`
	Emails                   json.RawMessage `json:"emails"`
	FirstName                string          `json:"firstName"`
	Groups                   json.RawMessage `json:"groups"`
	IncludeOnCalendarInvites bool            `json:"includeOnCalendarInvites"`
	LastName                 string          `json:"lastName"`
	LeadSource               string          `json:"leadSource"`
	NickName                 string          `json:"nickName"`
	Office                   json.RawMessage `json:"office"`
	Phones                   json.RawMessage `json:"phones"`
	PortalAccess             bool            `json:"portalAccess"`
	PortalRoleKey            string          `json:"portalRoleKey"`
	Prefix                   string          `json:"prefix"`
	RoleKey                  string          `json:"roleKey"`
	Suffix                   string          `json:"suffix"`
	Tags                     json.RawMessage `json:"tags"`
	Website                  string          `json:"website"`
}

type LinkDocument struct {
	Category           string          `json:"category"`
	FileRoleKey        string          `json:"fileRoleKey"`
	FileSize           int             `json:"fileSize"`
	MimeType           string          `json:"mimeType"`
	RequiredForClosing bool            `json:"requiredForClosing"`
	RoleAccess         json.RawMessage `json:"roleAccess"`
	StorageKey         string          `json:"storageKey"`
	Title              string          `json:"title"`
}

type MarkAllReadRequest struct {
	TcId string `json:"tcId"`
}

type MarkFieldDisputed struct {
	ConflictingValues json.RawMessage `json:"conflictingValues"`
	Reason            string          `json:"reason"`
}

type MarkFieldReviewed struct {
	ReviewedBy string `json:"reviewedBy"`
}

type MarkFieldStale struct {
	Reason string `json:"reason"`
}

type MarkStaleMarkAgentActionStaleResponse struct {
	Data json.RawMessage `json:"data"`
}

type MarkStaleRequest struct {
	Reason string `json:"reason"`
}

type Notification struct {
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`
	LinkTo    string `json:"linkTo"`
	ReadAt    string `json:"readAt"`
	TcId      string `json:"tcId"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

type NotificationsMarkAllReadResponse struct {
	Data json.RawMessage `json:"data"`
}

type PatchProfileRequest struct {
	BrokerageName          string `json:"brokerageName"`
	DailyDigestEmail       bool   `json:"dailyDigestEmail"`
	Name                   string `json:"name"`
	NotificationPreference string `json:"notificationPreference"`
	StateLicenseNumber     string `json:"stateLicenseNumber"`
}

type PortalAdoption struct {
	FirstViewAt   string `json:"firstViewAt"`
	LastViewAt    string `json:"lastViewAt"`
	TotalViews    int    `json:"totalViews"`
	TransactionId string `json:"transactionId"`
	UniqueViews   int    `json:"uniqueViews"`
}

type PortalCreateInviteResponse struct {
	Data json.RawMessage `json:"data"`
}

type PortalDocument struct {
	FileRoleKey string `json:"fileRoleKey"`
	Id          string `json:"id"`
	MimeType    string `json:"mimeType"`
	Status      string `json:"status"`
	Title       string `json:"title"`
	UploadedAt  string `json:"uploadedAt"`
}

type PortalExchangeTokenResponse struct {
	Data json.RawMessage `json:"data"`
}

type PortalInvite struct {
	ContactId     string `json:"contactId"`
	CreatedAt     string `json:"createdAt"`
	Email         string `json:"email"`
	ExpiresAt     string `json:"expiresAt"`
	Id            string `json:"id"`
	RevokedAt     string `json:"revokedAt"`
	RoleKey       string `json:"roleKey"`
	Token         string `json:"token"`
	TransactionId string `json:"transactionId"`
}

type PortalRevokeInviteResponse struct {
	Data json.RawMessage `json:"data"`
}

type PortalSession struct {
	ContactId     string `json:"contactId"`
	ExpiresAt     string `json:"expiresAt"`
	RoleKey       string `json:"roleKey"`
	SessionToken  string `json:"sessionToken"`
	TransactionId string `json:"transactionId"`
}

type PostmarkInboundEmail struct {
	Attachments       json.RawMessage `json:"Attachments"`
	Bcc               string          `json:"Bcc"`
	BccFull           json.RawMessage `json:"BccFull"`
	Cc                string          `json:"Cc"`
	CcFull            json.RawMessage `json:"CcFull"`
	From              string          `json:"From"`
	Headers           json.RawMessage `json:"Headers"`
	HtmlBody          string          `json:"HtmlBody"`
	MailboxHash       string          `json:"MailboxHash"`
	MessageID         string          `json:"MessageID"`
	OriginalRecipient string          `json:"OriginalRecipient"`
	StrippedTextReply string          `json:"StrippedTextReply"`
	Subject           string          `json:"Subject"`
	TextBody          string          `json:"TextBody"`
	To                string          `json:"To"`
	ToFull            json.RawMessage `json:"ToFull"`
}

type ProfileResponse struct {
	BrokerageName          string `json:"brokerageName"`
	DailyDigestEmail       bool   `json:"dailyDigestEmail"`
	Email                  string `json:"email"`
	Name                   string `json:"name"`
	NotificationPreference string `json:"notificationPreference"`
	StateLicenseNumber     string `json:"stateLicenseNumber"`
}

type PromptVersionAccuracy struct {
	AccuracyRate     float64 `json:"accuracyRate"`
	Corrections      int     `json:"corrections"`
	PromptVersion    string  `json:"promptVersion"`
	TotalExtractions int     `json:"totalExtractions"`
}

type ReadMarkNotificationResponse struct {
	Data json.RawMessage `json:"data"`
}

type RejectAgentActionResponse struct {
	Data json.RawMessage `json:"data"`
}

type RevokeAgentTokenResponse struct {
	Data json.RawMessage `json:"data"`
}

type SeenCallout struct {
	CalloutKey string `json:"calloutKey"`
	SeenAt     string `json:"seenAt"`
	UserId     string `json:"userId"`
}

type SetFieldValue struct {
	Confidence       float64 `json:"confidence"`
	Source           string  `json:"source"`
	SourceDocumentId string  `json:"sourceDocumentId"`
	SourcePage       int     `json:"sourcePage"`
	SourceQuote      string  `json:"sourceQuote"`
	Value            string  `json:"value"`
}

type StatusUpdateDocumentResponse struct {
	Data json.RawMessage `json:"data"`
}

type SubmitForm struct {
	SubmittedBy   string          `json:"submittedBy"`
	TransactionId string          `json:"transactionId"`
	Values        json.RawMessage `json:"values"`
}

type SubmitFormResponse struct {
	Data json.RawMessage `json:"data"`
}

type Task struct {
	AssignedRoles        json.RawMessage `json:"assignedRoles"`
	AssigneeContactId    string          `json:"assigneeContactId"`
	AssigneeId           string          `json:"assigneeId"`
	AssigneeTcId         string          `json:"assigneeTcId"`
	AssigneeType         string          `json:"assigneeType"`
	ClaimedAt            string          `json:"claimedAt"`
	ClaimedBy            string          `json:"claimedBy"`
	CreatedAt            string          `json:"createdAt"`
	DateRule             json.RawMessage `json:"dateRule"`
	Dependencies         json.RawMessage `json:"dependencies"`
	Description          string          `json:"description"`
	DueDate              string          `json:"dueDate"`
	Id                   string          `json:"id"`
	LockCondition        json.RawMessage `json:"lockCondition"`
	PortalVisible        bool            `json:"portalVisible"`
	Slug                 string          `json:"slug"`
	SourceCatalogId      string          `json:"sourceCatalogId"`
	SourceCatalogVersion int             `json:"sourceCatalogVersion"`
	Status               string          `json:"status"`
	SubTasks             json.RawMessage `json:"subTasks"`
	Tags                 json.RawMessage `json:"tags"`
	Title                string          `json:"title"`
	TransactionId        string          `json:"transactionId"`
	UpdatedAt            string          `json:"updatedAt"`
}

type TasksCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type TasksDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type TasksUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type Template struct {
	BuiltIn     bool   `json:"builtIn"`
	CreatedAt   string `json:"createdAt"`
	CreatedBy   string `json:"createdBy"`
	Data        string `json:"data"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	UpdatedAt   string `json:"updatedAt"`
}

type TemplatesCreateResponse struct {
	Data json.RawMessage `json:"data"`
}

type TemplatesDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type TemplatesGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type TemplatesUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type TransactionContact struct {
	Contact                  json.RawMessage `json:"contact"`
	ContactId                string          `json:"contactId"`
	IncludeOnCalendarInvites bool            `json:"includeOnCalendarInvites"`
	PortalAccess             bool            `json:"portalAccess"`
	PortalRoleKey            string          `json:"portalRoleKey"`
	RoleKey                  string          `json:"roleKey"`
	TransactionId            string          `json:"transactionId"`
}

type TransactionsConfirmCsvImportResponse struct {
	Data json.RawMessage `json:"data"`
}

type TransactionsCreateResponse struct {
	Data string `json:"data"`
}

type TransactionsDeleteResponse struct {
	Data json.RawMessage `json:"data"`
}

type TransactionsGetResponse struct {
	Data json.RawMessage `json:"data"`
}

type TransactionsPreviewCsvImportResponse struct {
	Data json.RawMessage `json:"data"`
}

type TransactionsUpdateResponse struct {
	Data json.RawMessage `json:"data"`
}

type UpdateContact struct {
	Address            json.RawMessage `json:"address"`
	AgentLicenseNumber string          `json:"agentLicenseNumber"`
	Emails             json.RawMessage `json:"emails"`
	Fax                string          `json:"fax"`
	FirstName          string          `json:"firstName"`
	Groups             json.RawMessage `json:"groups"`
	LastName           string          `json:"lastName"`
	LeadSource         string          `json:"leadSource"`
	NickName           string          `json:"nickName"`
	Office             json.RawMessage `json:"office"`
	Phones             json.RawMessage `json:"phones"`
	Prefix             string          `json:"prefix"`
	Suffix             string          `json:"suffix"`
	Tags               json.RawMessage `json:"tags"`
	Website            string          `json:"website"`
}

type UpdateDeal struct {
	Address    json.RawMessage `json:"address"`
	AssignedTo json.RawMessage `json:"assignedTo"`
	Status     string          `json:"status"`
	TeamId     string          `json:"teamId"`
	Type       string          `json:"type"`
}

type UpdateDocument struct {
	Category           string          `json:"category"`
	Classification     json.RawMessage `json:"classification"`
	RequiredForClosing bool            `json:"requiredForClosing"`
	RoleAccess         json.RawMessage `json:"roleAccess"`
	Title              string          `json:"title"`
}

type UpdateDocumentStatus struct {
	Status string `json:"status"`
}

type UpdateEmail struct {
	BodyHtml  string `json:"bodyHtml"`
	Status    string `json:"status"`
	Subject   string `json:"subject"`
	ToAddress string `json:"toAddress"`
}

type UpdateForm struct {
	Fields json.RawMessage `json:"fields"`
	Name   string          `json:"name"`
}

type UpdateTask struct {
	AssignedRoles        json.RawMessage `json:"assignedRoles"`
	AssigneeId           string          `json:"assigneeId"`
	AssigneeType         string          `json:"assigneeType"`
	DateRule             json.RawMessage `json:"dateRule"`
	Dependencies         json.RawMessage `json:"dependencies"`
	Description          string          `json:"description"`
	DueDate              string          `json:"dueDate"`
	LockCondition        json.RawMessage `json:"lockCondition"`
	PortalVisible        bool            `json:"portalVisible"`
	Slug                 string          `json:"slug"`
	SourceCatalogId      string          `json:"sourceCatalogId"`
	SourceCatalogVersion int             `json:"sourceCatalogVersion"`
	Status               string          `json:"status"`
	SubTasks             json.RawMessage `json:"subTasks"`
	Tags                 json.RawMessage `json:"tags"`
	Title                string          `json:"title"`
}

type UpdateTemplate struct {
	Data        string `json:"data"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

type UploadResponse struct {
	Document   json.RawMessage `json:"document"`
	StorageKey string          `json:"storageKey"`
}

type UsagesListAgentTokenResponse struct {
	Data json.RawMessage `json:"data"`
}

type VersionsListDocumentResponse struct {
	Data json.RawMessage `json:"data"`
}

type VersionsUploadDocumentResponse struct {
	Data json.RawMessage `json:"data"`
}

type WebhookDelivery struct {
	Attempt        int    `json:"attempt"`
	DeliveredAt    string `json:"deliveredAt"`
	Error          string `json:"error"`
	EventType      string `json:"eventType"`
	Id             string `json:"id"`
	MaxAttempts    int    `json:"maxAttempts"`
	StatusCode     int    `json:"statusCode"`
	SubscriptionId string `json:"subscriptionId"`
	Success        bool   `json:"success"`
}

type WebhookError struct {
	Code  string `json:"code"`
	Error string `json:"error"`
}

type WebhookSubscription struct {
	CreatedAt  string          `json:"createdAt"`
	Enabled    bool            `json:"enabled"`
	EventTypes json.RawMessage `json:"eventTypes"`
	Id         string          `json:"id"`
	UpdatedAt  string          `json:"updatedAt"`
	Url        string          `json:"url"`
}

type WebhooksCreateSubscriptionResponse struct {
	Data json.RawMessage `json:"data"`
}

type WebhooksDeleteSubscriptionResponse struct {
	Data json.RawMessage `json:"data"`
}

type WebhooksHandleInboundEmailResponse struct {
	Data string `json:"data"`
}

type WebhooksUpdateSubscriptionResponse struct {
	Data json.RawMessage `json:"data"`
}

type WeeklySummary struct {
	ApprovalsHandled int    `json:"approvalsHandled"`
	EmailsDrafted    int    `json:"emailsDrafted"`
	FieldsExtracted  int    `json:"fieldsExtracted"`
	TasksCreated     int    `json:"tasksCreated"`
	TcUserId         string `json:"tcUserId"`
	WeekEnd          string `json:"weekEnd"`
	WeekStart        string `json:"weekStart"`
}
