package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRenderCatalogTable_Golden locks the rendering of a worst-case
// row: backticks live inside the link text (Name and Skill columns),
// the description carries punctuation we don't want to over-escape
// (commas, parentheses, an apostrophe, a hyphen). If markdown escaping
// ever changes here, the table cell display in the README changes.
// The per-row format is the documented surface; protect it.
func TestRenderCatalogTable_Golden(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:        "hubspot-pp-cli",
			Category:    "sales-and-crm",
			API:         "HubSpot",
			Description: "Work with contacts, companies, deals, tickets, and pipelines.",
			Path:        "library/sales-and-crm/hubspot",
		},
	}

	got := renderCatalogTable(entries)

	want := `<!-- this section is generated by tools/generate-registry; do not hand-edit -->
| Name | Skill | Release | What it does |
|------|-------|---------|--------------|
| [` + "`hubspot-pp-cli`" + `](library/sales-and-crm/hubspot/) | [` + "`/pp-hubspot-pp-cli`" + `](cli-skills/pp-hubspot-pp-cli/SKILL.md) | [latest](https://github.com/mvanhorn/printing-press-library/releases/tag/hubspot-pp-cli-current) | Work with contacts, companies, deals, tickets, and pipelines. |
`

	if got != want {
		t.Errorf("renderCatalogTable mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
}

// TestFormatDescription covers the normalization rules: trim, collapse
// newlines (a description must fit one table cell), and ensure
// terminal punctuation. The "?" / "!" branch matters because some
// descriptions are written as questions and we shouldn't append a
// trailing period in that case.
func TestFormatDescription(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"trims and adds period", "  hello world  ", "hello world."},
		{"keeps existing period", "hello.", "hello."},
		{"keeps existing question mark", "really?", "really?"},
		{"keeps existing exclamation", "wow!", "wow!"},
		{"collapses LF newlines", "line one\nline two", "line one line two."},
		{"collapses CRLF newlines", "line one\r\nline two", "line one line two."},
		{"empty stays empty", "   ", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := formatDescription(tc.in); got != tc.want {
				t.Errorf("formatDescription(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestRegistryDescription(t *testing.T) {
	cases := []struct {
		name          string
		prior         string
		goreleaser    string
		ppDescription string
		want          string
	}{
		{
			name:          "curated copy wins over both fallbacks",
			prior:         "Curated catalog copy.",
			goreleaser:    "Goreleaser brews copy.",
			ppDescription: "Manifest copy.",
			want:          "Curated catalog copy.",
		},
		{
			name:          "bare-heading prior falls through to goreleaser",
			prior:         "# Introduction",
			goreleaser:    "Real catalog copy.",
			ppDescription: "Manifest copy.",
			want:          "Real catalog copy.",
		},
		{
			name:          "empty prior falls through to goreleaser",
			prior:         "",
			goreleaser:    "Goreleaser copy.",
			ppDescription: "Manifest copy.",
			want:          "Goreleaser copy.",
		},
		{
			name:          "empty prior and goreleaser fall through to pp manifest description (lawhub-shape repair)",
			prior:         "",
			goreleaser:    "",
			ppDescription: "Local-first LSAT practice analytics.",
			want:          "Local-first LSAT practice analytics.",
		},
		{
			name:          "bare-heading prior with empty goreleaser falls through to pp",
			prior:         "# Introduction",
			goreleaser:    "",
			ppDescription: "Manifest copy.",
			want:          "Manifest copy.",
		},
		{
			name:          "all empty returns empty (validation catches this separately)",
			prior:         "",
			goreleaser:    "",
			ppDescription: "",
			want:          "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := registryDescription(tc.prior, tc.goreleaser, tc.ppDescription); got != tc.want {
				t.Errorf("registryDescription(%q, %q, %q) = %q, want %q",
					tc.prior, tc.goreleaser, tc.ppDescription, got, tc.want)
			}
		})
	}
}

func TestSearchTerms(t *testing.T) {
	got := searchTerms(printingPressManifest{
		APIName:         "booking-com",
		DisplayName:     "Booking.com",
		CLIName:         "booking-com-pp-cli",
		Description:     "Search Booking.com hotels, scrape details and reviews.",
		AuthDescription: "Authenticated trips use cookie import.",
		NovelFeatures: []struct {
			Name        string `json:"name"`
			Command     string `json:"command"`
			Description string `json:"description"`
			Rationale   string `json:"rationale"`
		}{
			{
				Name:        "Compare two hotels side-by-side",
				Command:     "compare",
				Description: "Fetches detail and reviews for two hotels in parallel.",
				Rationale:   "Useful for lodging decisions.",
			},
		},
	})

	want := []string{
		"booking-com",
		"Booking.com",
		"booking-com-pp-cli",
		"Search Booking.com hotels, scrape details and reviews.",
		"Authenticated trips use cookie import.",
		"Compare two hotels side-by-side",
		"compare",
		"Fetches detail and reviews for two hotels in parallel.",
		"Useful for lodging decisions.",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("searchTerms mismatch\nwant: %#v\ngot:  %#v", want, got)
	}
}

// TestValidateEntries exercises the source-only validation that backs the
// --validate flag. The required-field set must stay in lockstep with the
// npm installer's parseRegistry contract — any new requiredString check
// added there should grow a case here.
func TestValidateEntries(t *testing.T) {
	mcpOK := &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: "api_key"}

	cases := []struct {
		name    string
		entries []RegistryEntry
		// wantSubstrs is a set of substrings that must appear in the joined
		// error report. Using substrings avoids brittle exact-match coupling
		// to the error-message phrasing while still pinning slug + field.
		wantSubstrs []string
		wantOK      bool
	}{
		{
			name: "valid entry passes",
			entries: []RegistryEntry{
				{Name: "ok", Category: "tools", API: "OK", Description: "Does things.", Path: "library/tools/ok"},
			},
			wantOK: true,
		},
		{
			name: "empty description fails with sources-checked message in resolution order",
			entries: []RegistryEntry{
				{Name: "lawhub", Category: "education", API: "LawHub", Description: "", Path: "library/education/lawhub"},
			},
			wantSubstrs: []string{
				"lawhub: description is empty",
				// Sources appear in fallback-resolution order: goreleaser
				// (second tier) is listed before .printing-press.json (third
				// tier), matching what registryDescription consults.
				".goreleaser.yaml brews description, .printing-press.json description",
			},
		},
		{
			name: "all-whitespace description fails (matches npm requiredString trim semantics)",
			entries: []RegistryEntry{
				{Name: "ws", Category: "tools", API: "WS", Description: "   \t\n  ", Path: "library/tools/ws"},
			},
			wantSubstrs: []string{"ws: description is empty"},
		},
		{
			name: "all-whitespace name reports under (unnamed) prefix",
			entries: []RegistryEntry{
				{Name: "  ", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantSubstrs: []string{"(unnamed): name is empty"},
		},
		{
			name: "all-whitespace mcp.auth_type fails",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: "   "},
				},
			},
			wantSubstrs: []string{"x: mcp.auth_type is empty"},
		},
		{
			name: "multiple entries each report independently",
			entries: []RegistryEntry{
				{Name: "a", Category: "tools", API: "A", Description: "", Path: "library/tools/a"},
				{Name: "b", Category: "tools", API: "B", Description: "", Path: "library/tools/b"},
				{Name: "c", Category: "tools", API: "C", Description: "Has desc.", Path: "library/tools/c"},
			},
			wantSubstrs: []string{
				"a: description is empty",
				"b: description is empty",
			},
		},
		{
			name: "missing mcp.binary fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "", Transports: []string{"stdio"}, AuthType: "api_key"},
				},
			},
			wantSubstrs: []string{"x: mcp.binary is empty"},
		},
		{
			name: "missing mcp.transports fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: nil, AuthType: "api_key"},
				},
			},
			wantSubstrs: []string{"x: mcp.transports is empty"},
		},
		{
			name: "missing mcp.auth_type fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: ""},
				},
			},
			wantSubstrs: []string{"x: mcp.auth_type is empty"},
		},
		{
			name: "non-mcp entry skips mcp checks",
			entries: []RegistryEntry{
				{Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantOK: true,
		},
		{
			name: "valid mcp block passes",
			entries: []RegistryEntry{
				{Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x", MCP: mcpOK},
			},
			wantOK: true,
		},
		{
			name: "unnamed entry reports under (unnamed) prefix",
			entries: []RegistryEntry{
				{Name: "", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantSubstrs: []string{"(unnamed): name is empty"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := validateEntries(tc.entries)
			joined := strings.Join(got, "\n")
			if tc.wantOK {
				if len(got) != 0 {
					t.Fatalf("validateEntries: want no errors, got:\n%s", joined)
				}
				return
			}
			for _, sub := range tc.wantSubstrs {
				if !strings.Contains(joined, sub) {
					t.Errorf("validateEntries: missing substring %q in output:\n%s", sub, joined)
				}
			}
		})
	}
}

// TestValidateEntries_IgnoresPriorCuratedValue is the regression test for
// the lawhub-shape bug. The validator must NOT accept an entry whose only
// non-empty description comes from a prior curated registry value — that
// path is exactly what masked the original bug. This is enforced by the
// caller (main passes an empty existing map), but we also assert
// validateEntries' own contract: it judges only what's in the entry struct.
func TestValidateEntries_IgnoresPriorCuratedValue(t *testing.T) {
	// Entry with an empty description (post-source-only resolution) must
	// fail validation regardless of any external curated value.
	entries := []RegistryEntry{
		{Name: "lawhub", Category: "education", API: "LawHub", Description: "", Path: "library/education/lawhub"},
	}
	got := validateEntries(entries)
	if len(got) == 0 {
		t.Fatal("validateEntries: expected failure for empty description, got none")
	}
}

// TestFilterEntriesBySlug pins the scoping the PR-time --validate gate
// relies on: only the named CLIs are validated, so a stale PR that doesn't
// touch an already-correct CLI is never failed for it (the agent-capture /
// tiktok-shop false-failure on PRs branched before those descriptions
// landed). Unmatched slugs are dropped silently (deleted/renamed CLIs).
func TestFilterEntriesBySlug(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "agent-capture", Category: "developer-tools", API: "Agent Capture", Path: "library/developer-tools/agent-capture", Description: ""},
		{Name: "tiktok-shop", Category: "commerce", API: "TikTok Shop", Path: "library/commerce/tiktok-shop", Description: ""},
		{Name: "exchangerate-api", Category: "finance", API: "ExchangeRate-API", Path: "library/finance/exchangerate-api", Description: "Currency conversion."},
	}

	t.Run("restricts to named slugs and excludes the rest", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"exchangerate-api"})
		if len(got) != 1 || got[0].Name != "exchangerate-api" {
			t.Fatalf("want only exchangerate-api, got %+v", got)
		}
		// The dropped agent-capture/tiktok-shop entries (empty description)
		// must not reach validateEntries, so a PR touching only
		// exchangerate-api validates clean.
		if errs := validateEntries(got); len(errs) != 0 {
			t.Errorf("want no errors for scoped clean entry, got: %v", errs)
		}
	})

	t.Run("a changed CLI with an empty description still fails", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"agent-capture"})
		if len(got) != 1 {
			t.Fatalf("want agent-capture in scope, got %+v", got)
		}
		if errs := validateEntries(got); len(errs) == 0 {
			t.Error("want failure for in-scope empty description, got none")
		}
	})

	t.Run("unmatched slug is ignored", func(t *testing.T) {
		if got := filterEntriesBySlug(entries, []string{"deleted-cli"}); len(got) != 0 {
			t.Fatalf("want empty for unmatched slug, got %+v", got)
		}
	})

	t.Run("whitespace around a slug is trimmed", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"  exchangerate-api  "})
		if len(got) != 1 || got[0].Name != "exchangerate-api" {
			t.Fatalf("want exchangerate-api matched after trim, got %+v", got)
		}
	})
}

// TestRenderCatalogCounts checks both pluralization branches and the
// happy multi-entry / multi-category path. The pluralization matters
// because the rendered string lands in human-readable prose; "1 CLIs
// across 1 categories" reads as a generator bug.
func TestRenderCatalogCounts(t *testing.T) {
	cases := []struct {
		name    string
		entries []RegistryEntry
		want    string
	}{
		{
			name:    "single CLI, single category",
			entries: []RegistryEntry{{Name: "a", Category: "x"}},
			want:    "1 CLI across 1 category.",
		},
		{
			name: "many CLIs, many categories",
			entries: []RegistryEntry{
				{Name: "a", Category: "x"},
				{Name: "b", Category: "y"},
				{Name: "c", Category: "x"},
			},
			want: "3 CLIs across 2 categories.",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := renderCatalogCounts(tc.entries)
			if !strings.HasSuffix(got, tc.want) {
				t.Errorf("renderCatalogCounts: want suffix %q, got:\n%s", tc.want, got)
			}
		})
	}
}

// TestUpdateReadme_RoundTrip verifies the splice preserves surrounding
// prose and that running the generator twice on the same input is a
// byte-level no-op (idempotence — the same property registry.json
// generation already guarantees, extended to README rendering).
func TestUpdateReadme_RoundTrip(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "espn", Category: "media-and-entertainment", Description: "Live scores.", Path: "library/media-and-entertainment/espn"},
	}

	src := `# Title

Intro prose.

<!-- catalog-counts:begin -->
old counts
<!-- catalog-counts:end -->

Middle prose.

<!-- catalog:begin -->
old table
<!-- catalog:end -->

Trailing prose.
`

	first, err := updateReadme([]byte(src), entries)
	if err != nil {
		t.Fatalf("first updateReadme: %v", err)
	}
	second, err := updateReadme(first, entries)
	if err != nil {
		t.Fatalf("second updateReadme: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("updateReadme not idempotent\nfirst:\n%s\nsecond:\n%s", first, second)
	}
	if !strings.Contains(string(first), "# Title") || !strings.Contains(string(first), "Intro prose.") || !strings.Contains(string(first), "Middle prose.") || !strings.Contains(string(first), "Trailing prose.") {
		t.Errorf("updateReadme dropped surrounding prose; got:\n%s", first)
	}
	if strings.Contains(string(first), "old table") || strings.Contains(string(first), "old counts") {
		t.Errorf("updateReadme failed to replace sentinel content; got:\n%s", first)
	}
}

// TestDetectMCPTransports covers the source-grep detection logic.
// Encoding the detection rule in tests guards against two regressions:
// (a) a future generator template renaming NewStreamableHTTPServer to a
//
//	differently-named entry point would silently flip every dual-transport
//	CLI back to stdio-only, and the test fails before the registry is
//	re-emitted.
//
// (b) the missing-binary fallback returning nil would cause the registry
//
//	to emit `"transports": null` instead of `["stdio"]`; we lock in the
//	non-nil ["stdio"] default so the JSON shape stays a real array.
func TestDetectMCPTransports(t *testing.T) {
	stdioOnlyMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	server.ServeStdio(s)
}
`
	dualTransportMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	switch *transport {
	case "stdio":
		server.ServeStdio(s)
	case "http":
		httpSrv := server.NewStreamableHTTPServer(s)
		_ = httpSrv.Start(":7777")
	}
}
`

	cases := []struct {
		name    string
		binary  string
		writeAt string // relative to cliDir; "" means don't write
		body    string
		want    []string
	}{
		{
			name:    "stdio-only binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    stdioOnlyMain,
			want:    []string{"stdio"},
		},
		{
			name:    "dual transport binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    dualTransportMain,
			want:    []string{"stdio", "http"},
		},
		{
			name:    "missing binary file falls back to stdio",
			binary:  "demo-pp-mcp",
			writeAt: "",
			want:    []string{"stdio"},
		},
		{
			name:    "empty binary name returns stdio without filesystem read",
			binary:  "",
			writeAt: "",
			want:    []string{"stdio"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cliDir := t.TempDir()
			if tc.writeAt != "" {
				path := filepath.Join(cliDir, tc.writeAt)
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatalf("mkdir: %v", err)
				}
				if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
					t.Fatalf("write main.go: %v", err)
				}
			}
			got := detectMCPTransports(cliDir, tc.binary)
			if len(got) != len(tc.want) {
				t.Fatalf("transports = %v, want %v", got, tc.want)
			}
			for i, v := range tc.want {
				if got[i] != v {
					t.Errorf("transports[%d] = %q, want %q", i, got[i], v)
				}
			}
		})
	}
}

// TestUpdateReadme_MissingSentinels ensures updateReadme errors out
// rather than silently no-oping when a README hasn't opted into the
// sentinel scheme. Silent no-op would let drift sneak back in.
func TestUpdateReadme_MissingSentinels(t *testing.T) {
	src := `# Title

No sentinels here.
`
	_, err := updateReadme([]byte(src), nil)
	if err == nil {
		t.Fatal("expected error when sentinels missing, got nil")
	}
	if !strings.Contains(err.Error(), "missing begin sentinel") {
		t.Errorf("expected missing-sentinel error, got: %v", err)
	}
}
