// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAddressCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "address",
		Short:  "Manage address",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAddressEnrichCmd(flags))
	cmd.AddCommand(newAddressSuggestAddressesCmd(flags))
	return cmd
}
