// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAdminCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "admin",
		Short:  "Operator metrics and dead-letter queue tools.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAdminDismissDlqentryCmd(flags))
	cmd.AddCommand(newAdminGetApprovalRateCmd(flags))
	cmd.AddCommand(newAdminGetFieldAccuracyCmd(flags))
	cmd.AddCommand(newAdminGetPortalAdoptionCmd(flags))
	cmd.AddCommand(newAdminGetPromptVersionAccuracyCmd(flags))
	cmd.AddCommand(newAdminGetRegressionSetCmd(flags))
	cmd.AddCommand(newAdminGetWeeklySummaryCmd(flags))
	cmd.AddCommand(newAdminListCorrectionsCmd(flags))
	cmd.AddCommand(newAdminListDlqCmd(flags))
	cmd.AddCommand(newAdminRetryDlqentryCmd(flags))
	return cmd
}
