// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAgentActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "agent-actions",
		Short:  "Approval queue proposals and review endpoints.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAgentActionsCreateCmd(flags))
	cmd.AddCommand(newAgentActionsInvalidateStaleActionsCmd(flags))
	cmd.AddCommand(newAgentActionsListCmd(flags))
	cmd.AddCommand(newAgentActionsAcceptContactSuggestionCmd(flags))
	cmd.AddCommand(newAgentActionsApproveCmd(flags))
	cmd.AddCommand(newAgentActionsDismissContactSuggestionCmd(flags))
	cmd.AddCommand(newAgentActionsMarkStaleCmd(flags))
	cmd.AddCommand(newAgentActionsRejectCmd(flags))
	return cmd
}
