// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAgentActionsAcceptContactSuggestionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "accept-contact-suggestion",
		Short: "Manage accept contact suggestion",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAgentActionsAcceptContactSuggestionAcceptContactSuggestionCmd(flags))
	return cmd
}
