// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAgentTokensCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "agent-tokens",
		Short:  "Manage agent tokens",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAgentTokensCreateCmd(flags))
	cmd.AddCommand(newAgentTokensListCmd(flags))
	cmd.AddCommand(newAgentTokensRevokeCmd(flags))
	cmd.AddCommand(newAgentTokensUsagesCmd(flags))
	return cmd
}
