// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAgentActionsApproveCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "approve",
		Short: "Manage approve",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAgentActionsApproveAgentActionCmd(flags))
	return cmd
}
