// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAgentActionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyIdempotencyKey string
	var bodyPayload string
	var bodyReasoning string
	var bodyResumeToken string
	var bodySourceDocumentId string
	var bodySourcePage int
	var bodySourceQuote string
	var bodyTransactionId string
	var bodyType string
	var bodyWorkflowRunId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create an agent action",
		Example:     "  theclose-pp-cli agent-actions create --reasoning example-value",
		Annotations: map[string]string{"pp:endpoint": "agent-actions.create", "pp:method": "POST", "pp:path": "/api/agent-actions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("payload") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "payload")
				}
				if !cmd.Flags().Changed("reasoning") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "reasoning")
				}
				if !cmd.Flags().Changed("source-page") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "source-page")
				}
				if !cmd.Flags().Changed("source-quote") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "source-quote")
				}
				if !cmd.Flags().Changed("transaction-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "transaction-id")
				}
				if !cmd.Flags().Changed("type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/agent-actions"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyIdempotencyKey != "" {
					body["idempotencyKey"] = bodyIdempotencyKey
				}
				if bodyPayload != "" {
					var parsedPayload any
					if err := json.Unmarshal([]byte(bodyPayload), &parsedPayload); err != nil {
						return fmt.Errorf("parsing --payload JSON: %w", err)
					}
					body["payload"] = parsedPayload
				}
				if bodyReasoning != "" {
					body["reasoning"] = bodyReasoning
				}
				if bodyResumeToken != "" {
					body["resumeToken"] = bodyResumeToken
				}
				if bodySourceDocumentId != "" {
					body["sourceDocumentId"] = bodySourceDocumentId
				}
				if bodySourcePage != 0 {
					body["sourcePage"] = bodySourcePage
				}
				if bodySourceQuote != "" {
					body["sourceQuote"] = bodySourceQuote
				}
				if bodyTransactionId != "" {
					body["transactionId"] = bodyTransactionId
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
				if bodyWorkflowRunId != "" {
					body["workflowRunId"] = bodyWorkflowRunId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "agent-actions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "Idempotency key")
	cmd.Flags().StringVar(&bodyPayload, "payload", "", "Payload")
	cmd.Flags().StringVar(&bodyReasoning, "reasoning", "", "Reasoning")
	cmd.Flags().StringVar(&bodyResumeToken, "resume-token", "", "Resume token")
	cmd.Flags().StringVar(&bodySourceDocumentId, "source-document-id", "", "Source document id")
	cmd.Flags().IntVar(&bodySourcePage, "source-page", 0, "Source page")
	cmd.Flags().StringVar(&bodySourceQuote, "source-quote", "", "Source quote")
	cmd.Flags().StringVar(&bodyTransactionId, "transaction-id", "", "Transaction id")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().StringVar(&bodyWorkflowRunId, "workflow-run-id", "", "Workflow run id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
