// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBillingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "billing",
		Short:  "Manage billing",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBillingCreateCheckoutSessionCmd(flags))
	cmd.AddCommand(newBillingCreatePortalSessionCmd(flags))
	cmd.AddCommand(newBillingGetSummaryCmd(flags))
	cmd.AddCommand(newBillingHandleStripeWebhookCmd(flags))
	return cmd
}
