// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCalloutsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "callouts",
		Short:  "Manage callouts",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCalloutsCheckSeenCmd(flags))
	cmd.AddCommand(newCalloutsListSeenCmd(flags))
	cmd.AddCommand(newCalloutsMarkSeenCmd(flags))
	return cmd
}
