// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConnectorActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "connector-actions",
		Short:  "Connector-backed task proposal, dry-run, approval, and audited execution records.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConnectorActionsApproveProposalCmd(flags))
	cmd.AddCommand(newConnectorActionsCreateProposalCmd(flags))
	cmd.AddCommand(newConnectorActionsDryRunCmd(flags))
	cmd.AddCommand(newConnectorActionsExecuteCmd(flags))
	cmd.AddCommand(newConnectorActionsGetProposalCmd(flags))
	return cmd
}
