// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newContactsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressState string
	var bodyAddressStreet string
	var bodyAddressUnit string
	var bodyAddressZip string
	var bodyAgentLicenseNumber string
	var bodyEmails string
	var bodyFax string
	var bodyFirstName string
	var bodyGroups string
	var bodyLastName string
	var bodyLeadSource string
	var bodyNickName string
	var bodyOfficeAddressCity string
	var bodyOfficeAddressState string
	var bodyOfficeAddressStreet string
	var bodyOfficeAddressUnit string
	var bodyOfficeAddressZip string
	var bodyOfficeName string
	var bodyOfficePhone string
	var bodyPhones string
	var bodyPrefix string
	var bodySuffix string
	var bodyTags string
	var bodyWebsite string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <id>",
		Short:       "Update a contact",
		Example:     "  theclose-pp-cli contacts update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "contacts.update", "pp:method": "PATCH", "pp:path": "/api/contacts/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/contacts/{id}"
			path = replacePathParam(path, "id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressState != "" {
						nestedAddress["state"] = bodyAddressState
					}
					if bodyAddressStreet != "" {
						nestedAddress["street"] = bodyAddressStreet
					}
					if bodyAddressUnit != "" {
						nestedAddress["unit"] = bodyAddressUnit
					}
					if bodyAddressZip != "" {
						nestedAddress["zip"] = bodyAddressZip
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				if bodyAgentLicenseNumber != "" {
					body["agentLicenseNumber"] = bodyAgentLicenseNumber
				}
				if bodyEmails != "" {
					var parsedEmails any
					if err := json.Unmarshal([]byte(bodyEmails), &parsedEmails); err != nil {
						return fmt.Errorf("parsing --emails JSON: %w", err)
					}
					body["emails"] = parsedEmails
				}
				if bodyFax != "" {
					body["fax"] = bodyFax
				}
				if bodyFirstName != "" {
					body["firstName"] = bodyFirstName
				}
				if bodyGroups != "" {
					var parsedGroups any
					if err := json.Unmarshal([]byte(bodyGroups), &parsedGroups); err != nil {
						return fmt.Errorf("parsing --groups JSON: %w", err)
					}
					body["groups"] = parsedGroups
				}
				if bodyLastName != "" {
					body["lastName"] = bodyLastName
				}
				if bodyLeadSource != "" {
					body["leadSource"] = bodyLeadSource
				}
				if bodyNickName != "" {
					body["nickName"] = bodyNickName
				}
				{
					nestedOffice := map[string]any{}
					{
						nestedOfficeAddress := map[string]any{}
						if bodyOfficeAddressCity != "" {
							nestedOfficeAddress["city"] = bodyOfficeAddressCity
						}
						if bodyOfficeAddressState != "" {
							nestedOfficeAddress["state"] = bodyOfficeAddressState
						}
						if bodyOfficeAddressStreet != "" {
							nestedOfficeAddress["street"] = bodyOfficeAddressStreet
						}
						if bodyOfficeAddressUnit != "" {
							nestedOfficeAddress["unit"] = bodyOfficeAddressUnit
						}
						if bodyOfficeAddressZip != "" {
							nestedOfficeAddress["zip"] = bodyOfficeAddressZip
						}
						if len(nestedOfficeAddress) > 0 {
							nestedOffice["address"] = nestedOfficeAddress
						}
					}
					if bodyOfficeName != "" {
						nestedOffice["name"] = bodyOfficeName
					}
					if bodyOfficePhone != "" {
						nestedOffice["phone"] = bodyOfficePhone
					}
					if len(nestedOffice) > 0 {
						body["office"] = nestedOffice
					}
				}
				if bodyPhones != "" {
					var parsedPhones any
					if err := json.Unmarshal([]byte(bodyPhones), &parsedPhones); err != nil {
						return fmt.Errorf("parsing --phones JSON: %w", err)
					}
					body["phones"] = parsedPhones
				}
				if bodyPrefix != "" {
					body["prefix"] = bodyPrefix
				}
				if bodySuffix != "" {
					body["suffix"] = bodySuffix
				}
				if bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					body["tags"] = parsedTags
				}
				if bodyWebsite != "" {
					body["website"] = bodyWebsite
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "contacts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "City")
	cmd.Flags().StringVar(&bodyAddressState, "address-state", "", "State")
	cmd.Flags().StringVar(&bodyAddressStreet, "address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAddressUnit, "address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAddressZip, "address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAgentLicenseNumber, "agent-license-number", "", "Agent license number")
	cmd.Flags().StringVar(&bodyEmails, "emails", "", "Emails")
	cmd.Flags().StringVar(&bodyFax, "fax", "", "Fax")
	cmd.Flags().StringVar(&bodyFirstName, "first-name", "", "First name")
	cmd.Flags().StringVar(&bodyGroups, "groups", "", "Groups")
	cmd.Flags().StringVar(&bodyLastName, "last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyLeadSource, "lead-source", "", "Lead source")
	cmd.Flags().StringVar(&bodyNickName, "nick-name", "", "Nick name")
	cmd.Flags().StringVar(&bodyOfficeAddressCity, "office-address-city", "", "City")
	cmd.Flags().StringVar(&bodyOfficeAddressState, "office-address-state", "", "State")
	cmd.Flags().StringVar(&bodyOfficeAddressStreet, "office-address-street", "", "Street")
	cmd.Flags().StringVar(&bodyOfficeAddressUnit, "office-address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyOfficeAddressZip, "office-address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyOfficeName, "office-name", "", "Name")
	cmd.Flags().StringVar(&bodyOfficePhone, "office-phone", "", "Phone")
	cmd.Flags().StringVar(&bodyPhones, "phones", "", "Phones")
	cmd.Flags().StringVar(&bodyPrefix, "prefix", "", "Prefix")
	cmd.Flags().StringVar(&bodySuffix, "suffix", "", "Suffix")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Tags")
	cmd.Flags().StringVar(&bodyWebsite, "website", "", "Website")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
