// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDocumentsVersionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "versions",
		Short: "Manage versions",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDocumentsVersionsListDocumentCmd(flags))
	cmd.AddCommand(newDocumentsVersionsUploadDocumentCmd(flags))
	return cmd
}
