// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDocumentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "documents",
		Short:  "Upload, version, and status management for documents.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDocumentsGetCmd(flags))
	cmd.AddCommand(newDocumentsSoftDeleteCmd(flags))
	cmd.AddCommand(newDocumentsUpdateCmd(flags))
	cmd.AddCommand(newDocumentsDownloadCmd(flags))
	cmd.AddCommand(newDocumentsStatusCmd(flags))
	cmd.AddCommand(newDocumentsVersionsCmd(flags))
	return cmd
}
