// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFormsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "forms",
		Short:  "Intake form creation and submissions.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFormsCreateCmd(flags))
	cmd.AddCommand(newFormsDeleteCmd(flags))
	cmd.AddCommand(newFormsGetCmd(flags))
	cmd.AddCommand(newFormsUpdateCmd(flags))
	cmd.AddCommand(newFormsSubmitCmd(flags))
	return cmd
}
