// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newIntakeCommitIntakeSessionCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressClosingDate string
	var bodyAddressCounty string
	var bodyAddressState string
	var bodyAddressStreet string
	var bodyAddressUnit string
	var bodyAddressZip string
	var bodyAgentContactId string
	var bodyAgentEmails string
	var bodyAgentFirstName string
	var bodyAgentLastName string
	var bodyClientContactId string
	var bodyClientEmails string
	var bodyClientFirstName string
	var bodyClientLastName string
	var bodyDocumentCategory string
	var bodyDocumentFileRoleKey string
	var bodyDocumentMetadata string
	var bodyDocumentRequiredForClosing bool
	var bodyDocumentRoleAccess string
	var bodyDocumentTitle string
	var bodyRawAddress string
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "intake-session <id>",
		Aliases:     []string{"create"},
		Short:       "Create a transaction from an intake session",
		Example:     "  theclose-pp-cli intake commit intake-session 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "commit.intake-session", "pp:method": "POST", "pp:path": "/api/intake/{id}/commit"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/intake/{id}/commit"
			path = replacePathParam(path, "id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressClosingDate != "" {
						nestedAddress["closingDate"] = bodyAddressClosingDate
					}
					if bodyAddressCounty != "" {
						nestedAddress["county"] = bodyAddressCounty
					}
					if bodyAddressState != "" {
						nestedAddress["state"] = bodyAddressState
					}
					if bodyAddressStreet != "" {
						nestedAddress["street"] = bodyAddressStreet
					}
					if bodyAddressUnit != "" {
						nestedAddress["unit"] = bodyAddressUnit
					}
					if bodyAddressZip != "" {
						nestedAddress["zip"] = bodyAddressZip
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				{
					nestedAgent := map[string]any{}
					if bodyAgentContactId != "" {
						nestedAgent["contactId"] = bodyAgentContactId
					}
					if bodyAgentEmails != "" {
						var parsedAgentEmails any
						if err := json.Unmarshal([]byte(bodyAgentEmails), &parsedAgentEmails); err != nil {
							return fmt.Errorf("parsing --agent-emails JSON: %w", err)
						}
						nestedAgent["emails"] = parsedAgentEmails
					}
					if bodyAgentFirstName != "" {
						nestedAgent["firstName"] = bodyAgentFirstName
					}
					if bodyAgentLastName != "" {
						nestedAgent["lastName"] = bodyAgentLastName
					}
					if len(nestedAgent) > 0 {
						body["agent"] = nestedAgent
					}
				}
				{
					nestedClient := map[string]any{}
					if bodyClientContactId != "" {
						nestedClient["contactId"] = bodyClientContactId
					}
					if bodyClientEmails != "" {
						var parsedClientEmails any
						if err := json.Unmarshal([]byte(bodyClientEmails), &parsedClientEmails); err != nil {
							return fmt.Errorf("parsing --client-emails JSON: %w", err)
						}
						nestedClient["emails"] = parsedClientEmails
					}
					if bodyClientFirstName != "" {
						nestedClient["firstName"] = bodyClientFirstName
					}
					if bodyClientLastName != "" {
						nestedClient["lastName"] = bodyClientLastName
					}
					if len(nestedClient) > 0 {
						body["client"] = nestedClient
					}
				}
				{
					nestedDocument := map[string]any{}
					if bodyDocumentCategory != "" {
						nestedDocument["category"] = bodyDocumentCategory
					}
					if bodyDocumentFileRoleKey != "" {
						nestedDocument["fileRoleKey"] = bodyDocumentFileRoleKey
					}
					if bodyDocumentMetadata != "" {
						var parsedDocumentMetadata any
						if err := json.Unmarshal([]byte(bodyDocumentMetadata), &parsedDocumentMetadata); err != nil {
							return fmt.Errorf("parsing --document-metadata JSON: %w", err)
						}
						nestedDocument["metadata"] = parsedDocumentMetadata
					}
					if bodyDocumentRequiredForClosing != false {
						nestedDocument["requiredForClosing"] = bodyDocumentRequiredForClosing
					}
					if bodyDocumentRoleAccess != "" {
						var parsedDocumentRoleAccess any
						if err := json.Unmarshal([]byte(bodyDocumentRoleAccess), &parsedDocumentRoleAccess); err != nil {
							return fmt.Errorf("parsing --document-role-access JSON: %w", err)
						}
						nestedDocument["roleAccess"] = parsedDocumentRoleAccess
					}
					if bodyDocumentTitle != "" {
						nestedDocument["title"] = bodyDocumentTitle
					}
					if len(nestedDocument) > 0 {
						body["document"] = nestedDocument
					}
				}
				if bodyRawAddress != "" {
					body["rawAddress"] = bodyRawAddress
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "commit",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "City")
	cmd.Flags().StringVar(&bodyAddressClosingDate, "address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyAddressCounty, "address-county", "", "County")
	cmd.Flags().StringVar(&bodyAddressState, "address-state", "", "State")
	cmd.Flags().StringVar(&bodyAddressStreet, "address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAddressUnit, "address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAddressZip, "address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAgentContactId, "agent-contact-id", "", "Contact id")
	cmd.Flags().StringVar(&bodyAgentEmails, "agent-emails", "", "Emails")
	cmd.Flags().StringVar(&bodyAgentFirstName, "agent-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyAgentLastName, "agent-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyClientContactId, "client-contact-id", "", "Contact id")
	cmd.Flags().StringVar(&bodyClientEmails, "client-emails", "", "Emails")
	cmd.Flags().StringVar(&bodyClientFirstName, "client-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyClientLastName, "client-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyDocumentCategory, "document-category", "", "Category")
	cmd.Flags().StringVar(&bodyDocumentFileRoleKey, "document-file-role-key", "", "File role key")
	cmd.Flags().StringVar(&bodyDocumentMetadata, "document-metadata", "", "Metadata")
	cmd.Flags().BoolVar(&bodyDocumentRequiredForClosing, "document-required-for-closing", false, "Required for closing")
	cmd.Flags().StringVar(&bodyDocumentRoleAccess, "document-role-access", "", "Role access")
	cmd.Flags().StringVar(&bodyDocumentTitle, "document-title", "", "Title")
	cmd.Flags().StringVar(&bodyRawAddress, "raw-address", "", "Raw address")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
