// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotificationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "notifications",
		Short:  "Notification feeds and read-state updates.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotificationsListCmd(flags))
	cmd.AddCommand(newNotificationsMarkAllReadCmd(flags))
	cmd.AddCommand(newNotificationsReadCmd(flags))
	return cmd
}
