// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEmailsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyBodyHtml string
	var bodyStatus string
	var bodySubject string
	var bodyToAddress string

	cmd := &cobra.Command{
		Use:         "emails <emailId>",
		Short:       "Update an email (edit draft, approve, reject)",
		Long:        "Shortcut for 'emails update'. Update an email (edit draft, approve, reject)",
		Example:     "  theclose-pp-cli emails 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "emails.update", "pp:method": "PATCH", "pp:path": "/api/emails/{emailId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/emails/{emailId}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "emailId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "emailId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("emailId is required\nUsage: %s <%s>", cmd.CommandPath(), "emailId"))
			}
			path = replacePathParam(path, "emailId", args[0])
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyBodyHtml != "" {
				body["bodyHtml"] = bodyBodyHtml
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodySubject != "" {
				body["subject"] = bodySubject
			}
			if bodyToAddress != "" {
				body["toAddress"] = bodyToAddress
			}
			data, _, err := c.Patch(path, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyBodyHtml, "body-html", "", "Body html")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Status")
	cmd.Flags().StringVar(&bodySubject, "subject", "", "Subject")
	cmd.Flags().StringVar(&bodyToAddress, "to-address", "", "To address")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
