// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEventsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagEventType string
	var flagActorType string
	var flagTransactionId string
	var flagLimit int
	var flagCursor string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "events",
		Short:       "Returns activity events across all transactions, newest first. Used by dashboard and NL context injection.",
		Long:        "Shortcut for 'events list-global'. Returns activity events across all transactions, newest first. Used by dashboard and NL context injection.",
		Example:     "  theclose-pp-cli events",
		Annotations: map[string]string{"pp:endpoint": "events.list-global", "pp:method": "GET", "pp:path": "/api/events", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("actor-type") {
				allowedActorType := []string{"user", "agent", "system", "contact"}
				validActorType := false
				for _, v := range allowedActorType {
					if flagActorType == v {
						validActorType = true
						break
					}
				}
				if !validActorType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "actor-type", flagActorType, allowedActorType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/events"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "events", path, map[string]string{
				"event_type":     fmt.Sprintf("%v", flagEventType),
				"actor_type":     fmt.Sprintf("%v", flagActorType),
				"transaction_id": fmt.Sprintf("%v", flagTransactionId),
				"limit":          fmt.Sprintf("%v", flagLimit),
				"cursor":         fmt.Sprintf("%v", flagCursor),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEventType, "event-type", "", "Filter by event type")
	cmd.Flags().StringVar(&flagActorType, "actor-type", "", "Filter by actor type (one of: user, agent, system, contact)")
	cmd.Flags().StringVar(&flagTransactionId, "transaction-id", "", "Filter by transaction ID")
	cmd.Flags().IntVar(&flagLimit, "limit", 50, "Max events to return (default 50, max 100)")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor for pagination (event ID to start after)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
