// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTasksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "Task queue and transaction coordination actions.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTasksDeleteCmd(flags))
	cmd.AddCommand(newTasksListAllCmd(flags))
	cmd.AddCommand(newTasksUpdateCmd(flags))
	cmd.AddCommand(newTasksReadyWorkCmd(flags))
	cmd.AddCommand(newTaskStatusCmd(flags, "claim", "in_progress"))
	cmd.AddCommand(newTaskStatusCmd(flags, "start", "in_progress"))
	cmd.AddCommand(newTaskStatusCmd(flags, "complete", "completed"))
	cmd.AddCommand(newTaskStatusCmd(flags, "skip", "skipped"))
	cmd.AddCommand(newTaskStatusCmd(flags, "block", "blocked"))
	cmd.AddCommand(newTaskStatusCmd(flags, "unblock", "open"))
	cmd.AddCommand(newTasksByDealCmd(flags))
	return cmd
}
