// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTasksListAllCmd(flags *rootFlags) *cobra.Command {
	var flagAssignee string
	var flagStatus string

	cmd := &cobra.Command{
		Use:         "list-all",
		Aliases:     []string{"list"},
		Short:       "Cross-deal task list for pipeline UI. Filter by assignee type or unassigned.",
		Example:     "  theclose-pp-cli tasks list-all",
		Annotations: map[string]string{"pp:endpoint": "tasks.list-all", "pp:method": "GET", "pp:path": "/api/tasks", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("assignee") {
				allowedAssignee := []string{"tc", "party", "agent", "unassigned"}
				validAssignee := false
				for _, v := range allowedAssignee {
					if flagAssignee == v {
						validAssignee = true
						break
					}
				}
				if !validAssignee {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "assignee", flagAssignee, allowedAssignee)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"open", "in_progress", "completed", "skipped", "blocked"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/tasks"
			params := map[string]string{}
			if flagAssignee != "" {
				params["assignee"] = fmt.Sprintf("%v", flagAssignee)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "tasks", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAssignee, "assignee", "", "Filter: tc (my tasks), party, agent, unassigned (one of: tc, party, agent, unassigned)")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Status (one of: open, in_progress, completed, skipped, blocked)")

	return cmd
}
