// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTemplatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "templates",
		Short:  "Template CRUD and application workflows.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTemplatesCreateCmd(flags))
	cmd.AddCommand(newTemplatesDeleteCmd(flags))
	cmd.AddCommand(newTemplatesGetCmd(flags))
	cmd.AddCommand(newTemplatesListCmd(flags))
	cmd.AddCommand(newTemplatesUpdateCmd(flags))
	cmd.AddCommand(newTemplatesApplyCmd(flags))
	return cmd
}
