// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTransactionsTasksCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignedRoles string
	var bodyAssigneeContactId string
	var bodyAssigneeId string
	var bodyAssigneeTcId string
	var bodyAssigneeType string
	var bodyDateRuleAnchorFieldKey string
	var bodyDateRuleAnchorFieldKeys string
	var bodyDateRuleDate string
	var bodyDateRuleDirection string
	var bodyDateRuleExpression string
	var bodyDateRuleOffsetBusinessDays int
	var bodyDateRuleType string
	var bodyDateRuleUnit string
	var bodyDependencies string
	var bodyDescription string
	var bodyDueDate string
	var bodyLockCondition string
	var bodyPortalVisible bool
	var bodySlug string
	var bodySourceCatalogId string
	var bodySourceCatalogVersion int
	var bodySubTasks string
	var bodyTags string
	var bodyTitle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <transactionId>",
		Short:       "Create a task",
		Example:     "  theclose-pp-cli transactions tasks create 550e8400-e29b-41d4-a716-446655440000 --title example-resource",
		Annotations: map[string]string{"pp:endpoint": "tasks.create", "pp:method": "POST", "pp:path": "/api/transactions/{transactionId}/tasks"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("date-rule-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "date-rule-type")
				}
				if !cmd.Flags().Changed("title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/transactions/{transactionId}/tasks"
			path = replacePathParam(path, "transactionId", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignedRoles != "" {
					var parsedAssignedRoles any
					if err := json.Unmarshal([]byte(bodyAssignedRoles), &parsedAssignedRoles); err != nil {
						return fmt.Errorf("parsing --assigned-roles JSON: %w", err)
					}
					body["assignedRoles"] = parsedAssignedRoles
				}
				if bodyAssigneeContactId != "" {
					body["assigneeContactId"] = bodyAssigneeContactId
				}
				if bodyAssigneeId != "" {
					body["assigneeId"] = bodyAssigneeId
				}
				if bodyAssigneeTcId != "" {
					body["assigneeTcId"] = bodyAssigneeTcId
				}
				if bodyAssigneeType != "" {
					body["assigneeType"] = bodyAssigneeType
				}
				{
					nestedDateRule := map[string]any{}
					if bodyDateRuleAnchorFieldKey != "" {
						nestedDateRule["anchorFieldKey"] = bodyDateRuleAnchorFieldKey
					}
					if bodyDateRuleAnchorFieldKeys != "" {
						var parsedDateRuleAnchorFieldKeys any
						if err := json.Unmarshal([]byte(bodyDateRuleAnchorFieldKeys), &parsedDateRuleAnchorFieldKeys); err != nil {
							return fmt.Errorf("parsing --date-rule-anchor-field-keys JSON: %w", err)
						}
						nestedDateRule["anchorFieldKeys"] = parsedDateRuleAnchorFieldKeys
					}
					if bodyDateRuleDate != "" {
						nestedDateRule["date"] = bodyDateRuleDate
					}
					if bodyDateRuleDirection != "" {
						nestedDateRule["direction"] = bodyDateRuleDirection
					}
					if bodyDateRuleExpression != "" {
						nestedDateRule["expression"] = bodyDateRuleExpression
					}
					if bodyDateRuleOffsetBusinessDays != 0 {
						nestedDateRule["offsetBusinessDays"] = bodyDateRuleOffsetBusinessDays
					}
					if bodyDateRuleType != "" {
						nestedDateRule["type"] = bodyDateRuleType
					}
					if bodyDateRuleUnit != "" {
						nestedDateRule["unit"] = bodyDateRuleUnit
					}
					if len(nestedDateRule) > 0 {
						body["dateRule"] = nestedDateRule
					}
				}
				if bodyDependencies != "" {
					var parsedDependencies any
					if err := json.Unmarshal([]byte(bodyDependencies), &parsedDependencies); err != nil {
						return fmt.Errorf("parsing --dependencies JSON: %w", err)
					}
					body["dependencies"] = parsedDependencies
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDueDate != "" {
					body["dueDate"] = bodyDueDate
				}
				if bodyLockCondition != "" {
					var parsedLockCondition any
					if err := json.Unmarshal([]byte(bodyLockCondition), &parsedLockCondition); err != nil {
						return fmt.Errorf("parsing --lock-condition JSON: %w", err)
					}
					body["lockCondition"] = parsedLockCondition
				}
				if bodyPortalVisible != false {
					body["portalVisible"] = bodyPortalVisible
				}
				if bodySlug != "" {
					body["slug"] = bodySlug
				}
				if bodySourceCatalogId != "" {
					body["sourceCatalogId"] = bodySourceCatalogId
				}
				if bodySourceCatalogVersion != 0 {
					body["sourceCatalogVersion"] = bodySourceCatalogVersion
				}
				if bodySubTasks != "" {
					var parsedSubTasks any
					if err := json.Unmarshal([]byte(bodySubTasks), &parsedSubTasks); err != nil {
						return fmt.Errorf("parsing --sub-tasks JSON: %w", err)
					}
					body["subTasks"] = parsedSubTasks
				}
				if bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					body["tags"] = parsedTags
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "tasks",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAssignedRoles, "assigned-roles", "", "Assigned roles")
	cmd.Flags().StringVar(&bodyAssigneeContactId, "assignee-contact-id", "", "Assignee contact id")
	cmd.Flags().StringVar(&bodyAssigneeId, "assignee-id", "", "Assignee id")
	cmd.Flags().StringVar(&bodyAssigneeTcId, "assignee-tc-id", "", "Assignee tc id")
	cmd.Flags().StringVar(&bodyAssigneeType, "assignee-type", "tc", "Assignee type")
	cmd.Flags().StringVar(&bodyDateRuleAnchorFieldKey, "date-rule-anchor-field-key", "", "Anchor field key")
	cmd.Flags().StringVar(&bodyDateRuleAnchorFieldKeys, "date-rule-anchor-field-keys", "", "Anchor field keys")
	cmd.Flags().StringVar(&bodyDateRuleDate, "date-rule-date", "", "Date")
	cmd.Flags().StringVar(&bodyDateRuleDirection, "date-rule-direction", "", "Direction")
	cmd.Flags().StringVar(&bodyDateRuleExpression, "date-rule-expression", "", "Expression")
	cmd.Flags().IntVar(&bodyDateRuleOffsetBusinessDays, "date-rule-offset-business-days", 0, "Offset business days")
	cmd.Flags().StringVar(&bodyDateRuleType, "date-rule-type", "", "Type")
	cmd.Flags().StringVar(&bodyDateRuleUnit, "date-rule-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyDependencies, "dependencies", "", "Dependencies")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyDueDate, "due-date", "", "Due date")
	cmd.Flags().StringVar(&bodyLockCondition, "lock-condition", "", "Lock condition")
	cmd.Flags().BoolVar(&bodyPortalVisible, "portal-visible", false, "Portal visible")
	cmd.Flags().StringVar(&bodySlug, "slug", "", "Slug")
	cmd.Flags().StringVar(&bodySourceCatalogId, "source-catalog-id", "", "Source catalog id")
	cmd.Flags().IntVar(&bodySourceCatalogVersion, "source-catalog-version", 0, "Source catalog version")
	cmd.Flags().StringVar(&bodySubTasks, "sub-tasks", "", "Sub tasks")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Tags")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Title")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
