// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTransactionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressClosingDate string
	var bodyAddressCounty string
	var bodyAddressState string
	var bodyAddressStreet string
	var bodyAddressUnit string
	var bodyAddressZip string
	var bodyAgentAddressCity string
	var bodyAgentAddressClosingDate string
	var bodyAgentAddressCounty string
	var bodyAgentAddressState string
	var bodyAgentAddressStreet string
	var bodyAgentAddressUnit string
	var bodyAgentAddressZip string
	var bodyAgentAgentLicenseNumber string
	var bodyAgentContactId string
	var bodyAgentEmails string
	var bodyAgentFax string
	var bodyAgentFirstName string
	var bodyAgentGroups string
	var bodyAgentLastName string
	var bodyAgentLeadSource string
	var bodyAgentNickName string
	var bodyAgentOfficeAddressCity string
	var bodyAgentOfficeAddressClosingDate string
	var bodyAgentOfficeAddressCounty string
	var bodyAgentOfficeAddressState string
	var bodyAgentOfficeAddressStreet string
	var bodyAgentOfficeAddressUnit string
	var bodyAgentOfficeAddressZip string
	var bodyAgentOfficeName string
	var bodyAgentOfficePhone string
	var bodyAgentPhones string
	var bodyAgentPrefix string
	var bodyAgentSuffix string
	var bodyAgentTags string
	var bodyAgentWebsite string
	var bodyAssignedTo string
	var bodyClientAddressCity string
	var bodyClientAddressClosingDate string
	var bodyClientAddressCounty string
	var bodyClientAddressState string
	var bodyClientAddressStreet string
	var bodyClientAddressUnit string
	var bodyClientAddressZip string
	var bodyClientAgentLicenseNumber string
	var bodyClientContactId string
	var bodyClientEmails string
	var bodyClientFax string
	var bodyClientFirstName string
	var bodyClientGroups string
	var bodyClientLastName string
	var bodyClientLeadSource string
	var bodyClientNickName string
	var bodyClientOfficeAddressCity string
	var bodyClientOfficeAddressClosingDate string
	var bodyClientOfficeAddressCounty string
	var bodyClientOfficeAddressState string
	var bodyClientOfficeAddressStreet string
	var bodyClientOfficeAddressUnit string
	var bodyClientOfficeAddressZip string
	var bodyClientOfficeName string
	var bodyClientOfficePhone string
	var bodyClientPhones string
	var bodyClientPrefix string
	var bodyClientSuffix string
	var bodyClientTags string
	var bodyClientWebsite string
	var bodyDateFieldsClosingDate string
	var bodyDateFieldsLeaseEndDate string
	var bodyDateFieldsLeaseStartDate string
	var bodyDateFieldsListingAgreementStartDate string
	var bodySourceIntakeId string
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a new deal",
		Example:     "  theclose-pp-cli transactions create",
		Annotations: map[string]string{"pp:endpoint": "transactions.create", "pp:method": "POST", "pp:path": "/api/transactions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/transactions"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressClosingDate != "" {
						nestedAddress["closingDate"] = bodyAddressClosingDate
					}
					if bodyAddressCounty != "" {
						nestedAddress["county"] = bodyAddressCounty
					}
					if bodyAddressState != "" {
						nestedAddress["state"] = bodyAddressState
					}
					if bodyAddressStreet != "" {
						nestedAddress["street"] = bodyAddressStreet
					}
					if bodyAddressUnit != "" {
						nestedAddress["unit"] = bodyAddressUnit
					}
					if bodyAddressZip != "" {
						nestedAddress["zip"] = bodyAddressZip
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				{
					nestedAgent := map[string]any{}
					{
						nestedAgentAddress := map[string]any{}
						if bodyAgentAddressCity != "" {
							nestedAgentAddress["city"] = bodyAgentAddressCity
						}
						if bodyAgentAddressClosingDate != "" {
							nestedAgentAddress["closingDate"] = bodyAgentAddressClosingDate
						}
						if bodyAgentAddressCounty != "" {
							nestedAgentAddress["county"] = bodyAgentAddressCounty
						}
						if bodyAgentAddressState != "" {
							nestedAgentAddress["state"] = bodyAgentAddressState
						}
						if bodyAgentAddressStreet != "" {
							nestedAgentAddress["street"] = bodyAgentAddressStreet
						}
						if bodyAgentAddressUnit != "" {
							nestedAgentAddress["unit"] = bodyAgentAddressUnit
						}
						if bodyAgentAddressZip != "" {
							nestedAgentAddress["zip"] = bodyAgentAddressZip
						}
						if len(nestedAgentAddress) > 0 {
							nestedAgent["address"] = nestedAgentAddress
						}
					}
					if bodyAgentAgentLicenseNumber != "" {
						nestedAgent["agentLicenseNumber"] = bodyAgentAgentLicenseNumber
					}
					if bodyAgentContactId != "" {
						nestedAgent["contactId"] = bodyAgentContactId
					}
					if bodyAgentEmails != "" {
						var parsedAgentEmails any
						if err := json.Unmarshal([]byte(bodyAgentEmails), &parsedAgentEmails); err != nil {
							return fmt.Errorf("parsing --agent-emails JSON: %w", err)
						}
						nestedAgent["emails"] = parsedAgentEmails
					}
					if bodyAgentFax != "" {
						nestedAgent["fax"] = bodyAgentFax
					}
					if bodyAgentFirstName != "" {
						nestedAgent["firstName"] = bodyAgentFirstName
					}
					if bodyAgentGroups != "" {
						var parsedAgentGroups any
						if err := json.Unmarshal([]byte(bodyAgentGroups), &parsedAgentGroups); err != nil {
							return fmt.Errorf("parsing --agent-groups JSON: %w", err)
						}
						nestedAgent["groups"] = parsedAgentGroups
					}
					if bodyAgentLastName != "" {
						nestedAgent["lastName"] = bodyAgentLastName
					}
					if bodyAgentLeadSource != "" {
						nestedAgent["leadSource"] = bodyAgentLeadSource
					}
					if bodyAgentNickName != "" {
						nestedAgent["nickName"] = bodyAgentNickName
					}
					{
						nestedAgentOffice := map[string]any{}
						{
							nestedAgentOfficeAddress := map[string]any{}
							if bodyAgentOfficeAddressCity != "" {
								nestedAgentOfficeAddress["city"] = bodyAgentOfficeAddressCity
							}
							if bodyAgentOfficeAddressClosingDate != "" {
								nestedAgentOfficeAddress["closingDate"] = bodyAgentOfficeAddressClosingDate
							}
							if bodyAgentOfficeAddressCounty != "" {
								nestedAgentOfficeAddress["county"] = bodyAgentOfficeAddressCounty
							}
							if bodyAgentOfficeAddressState != "" {
								nestedAgentOfficeAddress["state"] = bodyAgentOfficeAddressState
							}
							if bodyAgentOfficeAddressStreet != "" {
								nestedAgentOfficeAddress["street"] = bodyAgentOfficeAddressStreet
							}
							if bodyAgentOfficeAddressUnit != "" {
								nestedAgentOfficeAddress["unit"] = bodyAgentOfficeAddressUnit
							}
							if bodyAgentOfficeAddressZip != "" {
								nestedAgentOfficeAddress["zip"] = bodyAgentOfficeAddressZip
							}
							if len(nestedAgentOfficeAddress) > 0 {
								nestedAgentOffice["address"] = nestedAgentOfficeAddress
							}
						}
						if bodyAgentOfficeName != "" {
							nestedAgentOffice["name"] = bodyAgentOfficeName
						}
						if bodyAgentOfficePhone != "" {
							nestedAgentOffice["phone"] = bodyAgentOfficePhone
						}
						if len(nestedAgentOffice) > 0 {
							nestedAgent["office"] = nestedAgentOffice
						}
					}
					if bodyAgentPhones != "" {
						var parsedAgentPhones any
						if err := json.Unmarshal([]byte(bodyAgentPhones), &parsedAgentPhones); err != nil {
							return fmt.Errorf("parsing --agent-phones JSON: %w", err)
						}
						nestedAgent["phones"] = parsedAgentPhones
					}
					if bodyAgentPrefix != "" {
						nestedAgent["prefix"] = bodyAgentPrefix
					}
					if bodyAgentSuffix != "" {
						nestedAgent["suffix"] = bodyAgentSuffix
					}
					if bodyAgentTags != "" {
						var parsedAgentTags any
						if err := json.Unmarshal([]byte(bodyAgentTags), &parsedAgentTags); err != nil {
							return fmt.Errorf("parsing --agent-tags JSON: %w", err)
						}
						nestedAgent["tags"] = parsedAgentTags
					}
					if bodyAgentWebsite != "" {
						nestedAgent["website"] = bodyAgentWebsite
					}
					if len(nestedAgent) > 0 {
						body["agent"] = nestedAgent
					}
				}
				if bodyAssignedTo != "" {
					var parsedAssignedTo any
					if err := json.Unmarshal([]byte(bodyAssignedTo), &parsedAssignedTo); err != nil {
						return fmt.Errorf("parsing --assigned-to JSON: %w", err)
					}
					body["assignedTo"] = parsedAssignedTo
				}
				{
					nestedClient := map[string]any{}
					{
						nestedClientAddress := map[string]any{}
						if bodyClientAddressCity != "" {
							nestedClientAddress["city"] = bodyClientAddressCity
						}
						if bodyClientAddressClosingDate != "" {
							nestedClientAddress["closingDate"] = bodyClientAddressClosingDate
						}
						if bodyClientAddressCounty != "" {
							nestedClientAddress["county"] = bodyClientAddressCounty
						}
						if bodyClientAddressState != "" {
							nestedClientAddress["state"] = bodyClientAddressState
						}
						if bodyClientAddressStreet != "" {
							nestedClientAddress["street"] = bodyClientAddressStreet
						}
						if bodyClientAddressUnit != "" {
							nestedClientAddress["unit"] = bodyClientAddressUnit
						}
						if bodyClientAddressZip != "" {
							nestedClientAddress["zip"] = bodyClientAddressZip
						}
						if len(nestedClientAddress) > 0 {
							nestedClient["address"] = nestedClientAddress
						}
					}
					if bodyClientAgentLicenseNumber != "" {
						nestedClient["agentLicenseNumber"] = bodyClientAgentLicenseNumber
					}
					if bodyClientContactId != "" {
						nestedClient["contactId"] = bodyClientContactId
					}
					if bodyClientEmails != "" {
						var parsedClientEmails any
						if err := json.Unmarshal([]byte(bodyClientEmails), &parsedClientEmails); err != nil {
							return fmt.Errorf("parsing --client-emails JSON: %w", err)
						}
						nestedClient["emails"] = parsedClientEmails
					}
					if bodyClientFax != "" {
						nestedClient["fax"] = bodyClientFax
					}
					if bodyClientFirstName != "" {
						nestedClient["firstName"] = bodyClientFirstName
					}
					if bodyClientGroups != "" {
						var parsedClientGroups any
						if err := json.Unmarshal([]byte(bodyClientGroups), &parsedClientGroups); err != nil {
							return fmt.Errorf("parsing --client-groups JSON: %w", err)
						}
						nestedClient["groups"] = parsedClientGroups
					}
					if bodyClientLastName != "" {
						nestedClient["lastName"] = bodyClientLastName
					}
					if bodyClientLeadSource != "" {
						nestedClient["leadSource"] = bodyClientLeadSource
					}
					if bodyClientNickName != "" {
						nestedClient["nickName"] = bodyClientNickName
					}
					{
						nestedClientOffice := map[string]any{}
						{
							nestedClientOfficeAddress := map[string]any{}
							if bodyClientOfficeAddressCity != "" {
								nestedClientOfficeAddress["city"] = bodyClientOfficeAddressCity
							}
							if bodyClientOfficeAddressClosingDate != "" {
								nestedClientOfficeAddress["closingDate"] = bodyClientOfficeAddressClosingDate
							}
							if bodyClientOfficeAddressCounty != "" {
								nestedClientOfficeAddress["county"] = bodyClientOfficeAddressCounty
							}
							if bodyClientOfficeAddressState != "" {
								nestedClientOfficeAddress["state"] = bodyClientOfficeAddressState
							}
							if bodyClientOfficeAddressStreet != "" {
								nestedClientOfficeAddress["street"] = bodyClientOfficeAddressStreet
							}
							if bodyClientOfficeAddressUnit != "" {
								nestedClientOfficeAddress["unit"] = bodyClientOfficeAddressUnit
							}
							if bodyClientOfficeAddressZip != "" {
								nestedClientOfficeAddress["zip"] = bodyClientOfficeAddressZip
							}
							if len(nestedClientOfficeAddress) > 0 {
								nestedClientOffice["address"] = nestedClientOfficeAddress
							}
						}
						if bodyClientOfficeName != "" {
							nestedClientOffice["name"] = bodyClientOfficeName
						}
						if bodyClientOfficePhone != "" {
							nestedClientOffice["phone"] = bodyClientOfficePhone
						}
						if len(nestedClientOffice) > 0 {
							nestedClient["office"] = nestedClientOffice
						}
					}
					if bodyClientPhones != "" {
						var parsedClientPhones any
						if err := json.Unmarshal([]byte(bodyClientPhones), &parsedClientPhones); err != nil {
							return fmt.Errorf("parsing --client-phones JSON: %w", err)
						}
						nestedClient["phones"] = parsedClientPhones
					}
					if bodyClientPrefix != "" {
						nestedClient["prefix"] = bodyClientPrefix
					}
					if bodyClientSuffix != "" {
						nestedClient["suffix"] = bodyClientSuffix
					}
					if bodyClientTags != "" {
						var parsedClientTags any
						if err := json.Unmarshal([]byte(bodyClientTags), &parsedClientTags); err != nil {
							return fmt.Errorf("parsing --client-tags JSON: %w", err)
						}
						nestedClient["tags"] = parsedClientTags
					}
					if bodyClientWebsite != "" {
						nestedClient["website"] = bodyClientWebsite
					}
					if len(nestedClient) > 0 {
						body["client"] = nestedClient
					}
				}
				{
					nestedDateFields := map[string]any{}
					if bodyDateFieldsClosingDate != "" {
						nestedDateFields["closing_date"] = bodyDateFieldsClosingDate
					}
					if bodyDateFieldsLeaseEndDate != "" {
						nestedDateFields["lease_end_date"] = bodyDateFieldsLeaseEndDate
					}
					if bodyDateFieldsLeaseStartDate != "" {
						nestedDateFields["lease_start_date"] = bodyDateFieldsLeaseStartDate
					}
					if bodyDateFieldsListingAgreementStartDate != "" {
						nestedDateFields["listing_agreement_start_date"] = bodyDateFieldsListingAgreementStartDate
					}
					if len(nestedDateFields) > 0 {
						body["dateFields"] = nestedDateFields
					}
				}
				if bodySourceIntakeId != "" {
					body["sourceIntakeId"] = bodySourceIntakeId
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "transactions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "City")
	cmd.Flags().StringVar(&bodyAddressClosingDate, "address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyAddressCounty, "address-county", "", "County")
	cmd.Flags().StringVar(&bodyAddressState, "address-state", "", "State")
	cmd.Flags().StringVar(&bodyAddressStreet, "address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAddressUnit, "address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAddressZip, "address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAgentAddressCity, "agent-address-city", "", "City")
	cmd.Flags().StringVar(&bodyAgentAddressClosingDate, "agent-address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyAgentAddressCounty, "agent-address-county", "", "County")
	cmd.Flags().StringVar(&bodyAgentAddressState, "agent-address-state", "", "State")
	cmd.Flags().StringVar(&bodyAgentAddressStreet, "agent-address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAgentAddressUnit, "agent-address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAgentAddressZip, "agent-address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAgentAgentLicenseNumber, "agent-agent-license-number", "", "Agent license number")
	cmd.Flags().StringVar(&bodyAgentContactId, "agent-contact-id", "", "Contact id")
	cmd.Flags().StringVar(&bodyAgentEmails, "agent-emails", "", "Emails")
	cmd.Flags().StringVar(&bodyAgentFax, "agent-fax", "", "Fax")
	cmd.Flags().StringVar(&bodyAgentFirstName, "agent-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyAgentGroups, "agent-groups", "", "Groups")
	cmd.Flags().StringVar(&bodyAgentLastName, "agent-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyAgentLeadSource, "agent-lead-source", "", "Lead source")
	cmd.Flags().StringVar(&bodyAgentNickName, "agent-nick-name", "", "Nick name")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressCity, "agent-office-address-city", "", "City")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressClosingDate, "agent-office-address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressCounty, "agent-office-address-county", "", "County")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressState, "agent-office-address-state", "", "State")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressStreet, "agent-office-address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressUnit, "agent-office-address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAgentOfficeAddressZip, "agent-office-address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAgentOfficeName, "agent-office-name", "", "Name")
	cmd.Flags().StringVar(&bodyAgentOfficePhone, "agent-office-phone", "", "Phone")
	cmd.Flags().StringVar(&bodyAgentPhones, "agent-phones", "", "Phones")
	cmd.Flags().StringVar(&bodyAgentPrefix, "agent-prefix", "", "Prefix")
	cmd.Flags().StringVar(&bodyAgentSuffix, "agent-suffix", "", "Suffix")
	cmd.Flags().StringVar(&bodyAgentTags, "agent-tags", "", "Tags")
	cmd.Flags().StringVar(&bodyAgentWebsite, "agent-website", "", "Website")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "Assigned to")
	cmd.Flags().StringVar(&bodyClientAddressCity, "client-address-city", "", "City")
	cmd.Flags().StringVar(&bodyClientAddressClosingDate, "client-address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyClientAddressCounty, "client-address-county", "", "County")
	cmd.Flags().StringVar(&bodyClientAddressState, "client-address-state", "", "State")
	cmd.Flags().StringVar(&bodyClientAddressStreet, "client-address-street", "", "Street")
	cmd.Flags().StringVar(&bodyClientAddressUnit, "client-address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyClientAddressZip, "client-address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyClientAgentLicenseNumber, "client-agent-license-number", "", "Agent license number")
	cmd.Flags().StringVar(&bodyClientContactId, "client-contact-id", "", "Contact id")
	cmd.Flags().StringVar(&bodyClientEmails, "client-emails", "", "Emails")
	cmd.Flags().StringVar(&bodyClientFax, "client-fax", "", "Fax")
	cmd.Flags().StringVar(&bodyClientFirstName, "client-first-name", "", "First name")
	cmd.Flags().StringVar(&bodyClientGroups, "client-groups", "", "Groups")
	cmd.Flags().StringVar(&bodyClientLastName, "client-last-name", "", "Last name")
	cmd.Flags().StringVar(&bodyClientLeadSource, "client-lead-source", "", "Lead source")
	cmd.Flags().StringVar(&bodyClientNickName, "client-nick-name", "", "Nick name")
	cmd.Flags().StringVar(&bodyClientOfficeAddressCity, "client-office-address-city", "", "City")
	cmd.Flags().StringVar(&bodyClientOfficeAddressClosingDate, "client-office-address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyClientOfficeAddressCounty, "client-office-address-county", "", "County")
	cmd.Flags().StringVar(&bodyClientOfficeAddressState, "client-office-address-state", "", "State")
	cmd.Flags().StringVar(&bodyClientOfficeAddressStreet, "client-office-address-street", "", "Street")
	cmd.Flags().StringVar(&bodyClientOfficeAddressUnit, "client-office-address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyClientOfficeAddressZip, "client-office-address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyClientOfficeName, "client-office-name", "", "Name")
	cmd.Flags().StringVar(&bodyClientOfficePhone, "client-office-phone", "", "Phone")
	cmd.Flags().StringVar(&bodyClientPhones, "client-phones", "", "Phones")
	cmd.Flags().StringVar(&bodyClientPrefix, "client-prefix", "", "Prefix")
	cmd.Flags().StringVar(&bodyClientSuffix, "client-suffix", "", "Suffix")
	cmd.Flags().StringVar(&bodyClientTags, "client-tags", "", "Tags")
	cmd.Flags().StringVar(&bodyClientWebsite, "client-website", "", "Website")
	cmd.Flags().StringVar(&bodyDateFieldsClosingDate, "date-fields-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyDateFieldsLeaseEndDate, "date-fields-lease-end-date", "", "Lease end date")
	cmd.Flags().StringVar(&bodyDateFieldsLeaseStartDate, "date-fields-lease-start-date", "", "Lease start date")
	cmd.Flags().StringVar(&bodyDateFieldsListingAgreementStartDate, "date-fields-listing-agreement-start-date", "", "Listing agreement start date")
	cmd.Flags().StringVar(&bodySourceIntakeId, "source-intake-id", "", "Source intake id")
	cmd.Flags().StringVar(&bodyType, "type", "buyer_purchase", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
