// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTransactionsFieldsSetValueCmd(flags *rootFlags) *cobra.Command {
	var bodyConfidence float64
	var bodySource string
	var bodySourceDocumentId string
	var bodySourcePage int
	var bodySourceQuote string
	var bodyValue string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "set-value <transactionId> <fieldKey>",
		Aliases:     []string{"update"},
		Short:       "Triggers provenance storage and DateRule recalculation for dependent tasks.",
		Example:     "  theclose-pp-cli transactions fields set-value 550e8400-e29b-41d4-a716-446655440000 your-token-here",
		Annotations: map[string]string{"pp:endpoint": "fields.set-value", "pp:method": "PATCH", "pp:path": "/api/transactions/{transactionId}/fields/{fieldKey}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/transactions/{transactionId}/fields/{fieldKey}"
			path = replacePathParam(path, "transactionId", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("fieldKey is required\nUsage: %s <%s>", cmd.CommandPath(), "fieldKey"))
			}
			path = replacePathParam(path, "fieldKey", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyConfidence != 0.0 {
					body["confidence"] = bodyConfidence
				}
				if bodySource != "" {
					body["source"] = bodySource
				}
				if bodySourceDocumentId != "" {
					body["sourceDocumentId"] = bodySourceDocumentId
				}
				if bodySourcePage != 0 {
					body["sourcePage"] = bodySourcePage
				}
				if bodySourceQuote != "" {
					body["sourceQuote"] = bodySourceQuote
				}
				if bodyValue != "" {
					body["value"] = bodyValue
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "fields",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyConfidence, "confidence", 0.0, "Confidence")
	cmd.Flags().StringVar(&bodySource, "source", "tc_manual", "Source")
	cmd.Flags().StringVar(&bodySourceDocumentId, "source-document-id", "", "Source document id")
	cmd.Flags().IntVar(&bodySourcePage, "source-page", 0, "Source page")
	cmd.Flags().StringVar(&bodySourceQuote, "source-quote", "", "Source quote")
	cmd.Flags().StringVar(&bodyValue, "value", "", "Value")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
