// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsEmailFilterCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "email-filter",
		Short: "Manage email filter",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsEmailFilterConfirmTransactionInstallationCmd(flags))
	cmd.AddCommand(newTransactionsEmailFilterGetTransactionCmd(flags))
	return cmd
}
