// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "transactions",
		Short:  "Transaction lifecycle and search endpoints.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsConfirmCsvImportCmd(flags))
	cmd.AddCommand(newTransactionsCreateCmd(flags))
	cmd.AddCommand(newTransactionsDeleteCmd(flags))
	cmd.AddCommand(newTransactionsGetCmd(flags))
	cmd.AddCommand(newTransactionsListCmd(flags))
	cmd.AddCommand(newTransactionsPreviewCsvImportCmd(flags))
	cmd.AddCommand(newTransactionsUpdateCmd(flags))
	cmd.AddCommand(newTransactionsCapturedEmailsCmd(flags))
	cmd.AddCommand(newTransactionsContactsCmd(flags))
	cmd.AddCommand(newTransactionsDocumentsCmd(flags))
	cmd.AddCommand(newTransactionsEmailFilterCmd(flags))
	cmd.AddCommand(newTransactionsEmailsCmd(flags))
	cmd.AddCommand(newTransactionsEventsCmd(flags))
	cmd.AddCommand(newTransactionsFieldsCmd(flags))
	cmd.AddCommand(newTransactionsPortalCmd(flags))
	cmd.AddCommand(newTransactionsTasksCmd(flags))
	return cmd
}
