// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsEmailsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "emails",
		Short: "Manage emails",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsEmailsDraftCmd(flags))
	cmd.AddCommand(newTransactionsEmailsListCmd(flags))
	return cmd
}
