// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsFieldsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "fields",
		Short: "Structured extraction outputs and field review actions.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsFieldsBatchWriteCmd(flags))
	cmd.AddCommand(newTransactionsFieldsListValuesCmd(flags))
	cmd.AddCommand(newTransactionsFieldsMarkDisputedCmd(flags))
	cmd.AddCommand(newTransactionsFieldsMarkReviewedCmd(flags))
	cmd.AddCommand(newTransactionsFieldsMarkStaleCmd(flags))
	cmd.AddCommand(newTransactionsFieldsReviewSummaryCmd(flags))
	cmd.AddCommand(newTransactionsFieldsSetValueCmd(flags))
	return cmd
}
