// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsPortalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "portal",
		Short: "Shared document portal invitations and access.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsPortalCreateInviteCmd(flags))
	cmd.AddCommand(newTransactionsPortalListDocumentsCmd(flags))
	cmd.AddCommand(newTransactionsPortalRevokeInviteCmd(flags))
	return cmd
}
