// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTransactionsListCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagStatus string
	var flagHealth string
	var flagClosingBefore string
	var flagClosingAfter string
	var flagArchive bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Returns deals ordered by health. Supports search (?q=), status filter, health filter, and closing date range.",
		Example:     "  theclose-pp-cli transactions list",
		Annotations: map[string]string{"pp:endpoint": "transactions.list", "pp:method": "GET", "pp:path": "/api/transactions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"lead", "listing_prep", "active", "active_listing", "under_contract", "pending", "closed", "terminated", "withdrawn", "on_hold"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			if cmd.Flags().Changed("health") {
				allowedHealth := []string{"CRITICAL", "AT_RISK", "ON_TRACK", "STALLED", "UNKNOWN"}
				validHealth := false
				for _, v := range allowedHealth {
					if flagHealth == v {
						validHealth = true
						break
					}
				}
				if !validHealth {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "health", flagHealth, allowedHealth)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/transactions"
			params := map[string]string{}
			if flagQ != "" {
				params["q"] = fmt.Sprintf("%v", flagQ)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagHealth != "" {
				params["health"] = fmt.Sprintf("%v", flagHealth)
			}
			if flagClosingBefore != "" {
				params["closing_before"] = fmt.Sprintf("%v", flagClosingBefore)
			}
			if flagClosingAfter != "" {
				params["closing_after"] = fmt.Sprintf("%v", flagClosingAfter)
			}
			if flagArchive != false {
				params["archive"] = fmt.Sprintf("%v", flagArchive)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "transactions", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Full-text search across address fields")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter by lifecycle status (one of: lead, listing_prep, active, active_listing, under_contract, pending, closed, terminated, withdrawn, on_hold)")
	cmd.Flags().StringVar(&flagHealth, "health", "", "Filter by health badge (one of: CRITICAL, AT_RISK, ON_TRACK, STALLED, UNKNOWN)")
	cmd.Flags().StringVar(&flagClosingBefore, "closing-before", "", "Closing date before (ISO date)")
	cmd.Flags().StringVar(&flagClosingAfter, "closing-after", "", "Closing date after (ISO date)")
	cmd.Flags().BoolVar(&flagArchive, "archive", false, "Include archived (closed/terminated/withdrawn) deals")

	return cmd
}
