// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsDocumentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "documents",
		Short: "Upload, version, and status management for documents.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsDocumentsLinkCmd(flags))
	cmd.AddCommand(newTransactionsDocumentsListCmd(flags))
	cmd.AddCommand(newTransactionsDocumentsUploadCmd(flags))
	return cmd
}
