// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsContactsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "contacts",
		Short: "Party and vendor contact records.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsContactsLinkToTransactionCmd(flags))
	cmd.AddCommand(newTransactionsContactsListTransactionCmd(flags))
	return cmd
}
