// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransactionsEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "events",
		Short: "Activity timeline feeds and streaming updates.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransactionsEventsCreateActivityCmd(flags))
	cmd.AddCommand(newTransactionsEventsListTransactionCmd(flags))
	cmd.AddCommand(newTransactionsEventsStreamTransactionCmd(flags))
	return cmd
}
