// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTransactionsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressClosingDate string
	var bodyAddressCounty string
	var bodyAddressState string
	var bodyAddressStreet string
	var bodyAddressUnit string
	var bodyAddressZip string
	var bodyAssignedTo string
	var bodyStatus string
	var bodyTeamId string
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <id>",
		Short:       "Status changes are validated against the deal state machine. Invalid transitions return 422.",
		Example:     "  theclose-pp-cli transactions update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "transactions.update", "pp:method": "PATCH", "pp:path": "/api/transactions/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/transactions/{id}"
			path = replacePathParam(path, "id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressClosingDate != "" {
						nestedAddress["closingDate"] = bodyAddressClosingDate
					}
					if bodyAddressCounty != "" {
						nestedAddress["county"] = bodyAddressCounty
					}
					if bodyAddressState != "" {
						nestedAddress["state"] = bodyAddressState
					}
					if bodyAddressStreet != "" {
						nestedAddress["street"] = bodyAddressStreet
					}
					if bodyAddressUnit != "" {
						nestedAddress["unit"] = bodyAddressUnit
					}
					if bodyAddressZip != "" {
						nestedAddress["zip"] = bodyAddressZip
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				if bodyAssignedTo != "" {
					var parsedAssignedTo any
					if err := json.Unmarshal([]byte(bodyAssignedTo), &parsedAssignedTo); err != nil {
						return fmt.Errorf("parsing --assigned-to JSON: %w", err)
					}
					body["assignedTo"] = parsedAssignedTo
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				if bodyTeamId != "" {
					body["teamId"] = bodyTeamId
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "transactions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "City")
	cmd.Flags().StringVar(&bodyAddressClosingDate, "address-closing-date", "", "Closing date")
	cmd.Flags().StringVar(&bodyAddressCounty, "address-county", "", "County")
	cmd.Flags().StringVar(&bodyAddressState, "address-state", "", "State")
	cmd.Flags().StringVar(&bodyAddressStreet, "address-street", "", "Street")
	cmd.Flags().StringVar(&bodyAddressUnit, "address-unit", "", "Unit")
	cmd.Flags().StringVar(&bodyAddressZip, "address-zip", "", "Zip")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "Assigned to")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Status")
	cmd.Flags().StringVar(&bodyTeamId, "team-id", "", "Team id")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
