// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhooksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "webhooks",
		Short:  "Webhook subscriptions and delivery history.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWebhooksCreateSubscriptionCmd(flags))
	cmd.AddCommand(newWebhooksDeleteSubscriptionCmd(flags))
	cmd.AddCommand(newWebhooksHandleInboundEmailCmd(flags))
	cmd.AddCommand(newWebhooksListDeliveriesCmd(flags))
	cmd.AddCommand(newWebhooksListSubscriptionsCmd(flags))
	cmd.AddCommand(newWebhooksUpdateSubscriptionCmd(flags))
	return cmd
}
