// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "address enrich", Description: "Enrich a partial address with missing structured fields", Group: "address"},
	{Command: "address suggest-addresses", Description: "Suggest address matches for autocomplete", Group: "address"},
	{Command: "admin dismiss-dlqentry", Description: "Removes a failed job from the DLQ without retrying.", Group: "admin"},
	{Command: "admin get-approval-rate", Description: "TC approval rate (trust test)", Group: "admin"},
	{Command: "admin get-field-accuracy", Description: "Most-corrected fields across all transactions. TC-owner only.", Group: "admin"},
	{Command: "admin get-portal-adoption", Description: "Portal adoption — unique external views", Group: "admin"},
	{Command: "admin get-prompt-version-accuracy", Description: "Accuracy stats per prompt version for before/after comparison.", Group: "admin"},
	{Command: "admin get-regression-set", Description: "Top 10 most-corrected fields to test before prompt updates.", Group: "admin"},
	{Command: "admin get-weekly-summary", Description: "VA replacement proxy — weekly action summary", Group: "admin"},
	{Command: "admin list-corrections", Description: "Full correction log with original AI values and TC corrections.", Group: "admin"},
	{Command: "admin list-dlq", Description: "Returns failed jobs across all queues. TC-owner only.", Group: "admin"},
	{Command: "admin retry-dlqentry", Description: "Re-enqueues a failed job for processing.", Group: "admin"},
	{Command: "agent-actions create", Description: "Create an agent action", Group: "agent-actions"},
	{Command: "agent-actions invalidate-stale-actions", Description: "Checks all pending actions for a transaction and marks matching ones as stale based on staleness rules.", Group: "agent-actions"},
	{Command: "agent-actions list", Description: "Returns agent actions, optionally filtered by deal or status.", Group: "agent-actions"},
	{Command: "agent-actions accept-contact-suggestion accept_contact_suggestion", Description: "Creates or links the suggested contact to the transaction and triggers email filter regeneration.", Group: "agent-actions"},
	{Command: "agent-actions approve agent-action", Description: "Approve an agent action", Group: "agent-actions"},
	{Command: "agent-actions dismiss-contact-suggestion dismiss_contact_suggestion", Description: "Rejects the contact suggestion without creating or linking a contact.", Group: "agent-actions"},
	{Command: "agent-actions mark-stale mark-agent-action-stale", Description: "Marks a pending action as stale when transaction state has changed, preventing approval until dismissed or edited.", Group: "agent-actions"},
	{Command: "agent-actions reject agent-action", Description: "Reject an agent action", Group: "agent-actions"},
	{Command: "agent-tokens create", Description: "Create a scoped API token", Group: "agent-tokens"},
	{Command: "agent-tokens list", Description: "List API tokens for the signed-in TC", Group: "agent-tokens"},
	{Command: "agent-tokens revoke agent-token", Description: "Revoke a token", Group: "agent-tokens"},
	{Command: "agent-tokens usages list-agent-token", Description: "List usage entries for a token", Group: "agent-tokens"},
	{Command: "actions propose", Description: "Create a connector action proposal through The Close", Group: "actions"},
	{Command: "actions dry-run", Description: "Run a connector action proposal dry-run without provider writes", Group: "actions"},
	{Command: "actions status", Description: "Read connector action proposal status", Group: "actions"},
	{Command: "actions execute", Description: "Execute an approved connector action through The Close", Group: "actions"},
	{Command: "actions audit", Description: "Show The Close audit events for a connector action proposal", Group: "actions"},
	{Command: "billing create-checkout-session", Description: "Create a Stripe checkout session for plan changes", Group: "billing"},
	{Command: "billing create-portal-session", Description: "Create a Stripe customer portal session", Group: "billing"},
	{Command: "billing get-summary", Description: "Get current billing summary", Group: "billing"},
	{Command: "billing handle-stripe-webhook", Description: "Stripe webhook for subscription lifecycle events", Group: "billing"},
	{Command: "callouts check-seen", Description: "Check whether a specific callout has been seen", Group: "callouts"},
	{Command: "callouts list-seen", Description: "List dismissed callout keys for the authenticated user", Group: "callouts"},
	{Command: "callouts mark-seen", Description: "Mark a callout key as seen (dismissed) for the authenticated user", Group: "callouts"},
	{Command: "close-developer-health get", Description: "Returns the process health and confirms the API runtime is responsive.", Group: "close-developer-health"},
	{Command: "close-developer-profile get", Description: "Get the signed-in TC profile", Group: "close-developer-profile"},
	{Command: "close-developer-profile patch", Description: "Update the signed-in TC profile", Group: "close-developer-profile"},
	{Command: "connector-actions approve-proposal", Description: "Approve a connector action proposal", Group: "connector-actions"},
	{Command: "connector-actions create-proposal", Description: "Create a connector action proposal", Group: "connector-actions"},
	{Command: "connector-actions dry-run", Description: "Run a connector action dry-run", Group: "connector-actions"},
	{Command: "connector-actions execute", Description: "Execute an approved connector action", Group: "connector-actions"},
	{Command: "connector-actions get-proposal", Description: "Read connector action proposal status", Group: "connector-actions"},
	{Command: "contacts create", Description: "Create a contact", Group: "contacts"},
	{Command: "contacts delete", Description: "Delete a contact", Group: "contacts"},
	{Command: "contacts get", Description: "Get contact by ID", Group: "contacts"},
	{Command: "contacts list", Description: "List contacts", Group: "contacts"},
	{Command: "contacts update", Description: "Update a contact", Group: "contacts"},
	{Command: "documents get", Description: "Get document by ID", Group: "documents"},
	{Command: "documents soft-delete", Description: "Marks document as deleted. S3 object is retained.", Group: "documents"},
	{Command: "documents update", Description: "Update document metadata", Group: "documents"},
	{Command: "documents download document", Description: "Returns a short-lived signed URL for downloading the document.", Group: "documents"},
	{Command: "documents status update-document", Description: "Update document status (approve, reject)", Group: "documents"},
	{Command: "documents versions list-document", Description: "List version history for a document", Group: "documents"},
	{Command: "documents versions upload-document", Description: "Replaces the current version. Old version is superseded, not deleted. Provenance to old version is preserved.", Group: "documents"},
	{Command: "events list-global", Description: "Returns activity events across all transactions, newest first. Used by dashboard and NL context injection.", Group: "events"},
	{Command: "forms create", Description: "Create an intake form", Group: "forms"},
	{Command: "forms delete", Description: "Delete a form", Group: "forms"},
	{Command: "forms get", Description: "Get a form by ID", Group: "forms"},
	{Command: "forms update", Description: "Update a form", Group: "forms"},
	{Command: "forms submit form", Description: "Public submission endpoint. Maps values to field definitions and auto-populates deal fields.", Group: "forms"},
	{Command: "fub propose-contact-upsert", Description: "Create a The Close proposal to create or update a Follow Up Boss contact", Group: "fub"},
	{Command: "fub propose-note-create", Description: "Create a The Close proposal to add a Follow Up Boss note", Group: "fub"},
	{Command: "fub propose-deal-create", Description: "Create a The Close proposal to create a Follow Up Boss deal", Group: "fub"},
	{Command: "fub propose-stage-update", Description: "Create a The Close proposal to update a Follow Up Boss deal stage", Group: "fub"},
	{Command: "fub propose-deal-delete", Description: "Create an approval-sensitive The Close proposal to delete or archive a Follow Up Boss deal", Group: "fub"},
	{Command: "intake get-session", Description: "Get intake extraction status", Group: "intake"},
	{Command: "intake undo-auto-created-transaction", Description: "Undo an auto-created transaction from a forwarded contract", Group: "intake"},
	{Command: "intake upload-contract-for", Description: "Accepts server-side multipart PDF upload, stores the file, creates an intake session, and enqueues extraction.", Group: "intake"},
	{Command: "intake cancel intake-session", Description: "Cancel an intake extraction", Group: "intake"},
	{Command: "intake commit intake-session", Description: "Create a transaction from an intake session", Group: "intake"},
	{Command: "notifications list", Description: "Returns notifications ordered with unread first, then by recency. Supports filtering by type.", Group: "notifications"},
	{Command: "notifications mark-all-read", Description: "Mark all notifications as read for a TC", Group: "notifications"},
	{Command: "notifications read mark-notification", Description: "Mark a notification as read", Group: "notifications"},
	{Command: "search", Description: "Full-text search across locally synced The Close data", Group: "local"},
	{Command: "sync", Description: "Sync The Close API data into local SQLite for search and work queues", Group: "local"},
	{Command: "work-queue overdue", Description: "List overdue open tasks from synced data", Group: "work-queue"},
	{Command: "work-queue blocked", Description: "List blocked tasks from synced data", Group: "work-queue"},
	{Command: "work-queue needs-approval", Description: "List pending approval actions from synced data", Group: "work-queue"},
	{Command: "work-queue closing-soon", Description: "List deals closing soon from synced data", Group: "work-queue"},
	{Command: "work-queue missing-fields", Description: "List missing or empty deal fields from synced data", Group: "work-queue"},
	{Command: "work-queue stale-actions", Description: "List stale agent actions from synced data", Group: "work-queue"},
	{Command: "portal exchange-token", Description: "Validates the magic link JWT and returns a short-lived session token for portal API access.", Group: "portal"},
	{Command: "schema list-field-definitions", Description: "Returns every FieldDefinition. Agents call this to self-document available fields before acting on a transaction.", Group: "schema"},
	{Command: "tasks delete", Description: "Delete a task", Group: "tasks"},
	{Command: "tasks list-all", Description: "Cross-deal task list for pipeline UI. Filter by assignee type or unassigned.", Group: "tasks"},
	{Command: "tasks update", Description: "Update a task", Group: "tasks"},
	{Command: "templates create", Description: "Create a custom template", Group: "templates"},
	{Command: "templates delete", Description: "Built-in templates cannot be deleted.", Group: "templates"},
	{Command: "templates get", Description: "Get template by ID", Group: "templates"},
	{Command: "templates list", Description: "Browse template library, optionally filtered by type.", Group: "templates"},
	{Command: "templates update", Description: "Update a template", Group: "templates"},
	{Command: "templates apply template", Description: "Clones template data into the deal. Does not link — changes to the template won't affect the deal.", Group: "templates"},
	{Command: "transactions confirm-csv-import", Description: "Creates transactions in bulk from CSV rows. Import is additive only and each imported field is tagged with source=csv_import provenance.", Group: "transactions"},
	{Command: "transactions create", Description: "Create a new deal", Group: "transactions"},
	{Command: "transactions delete", Description: "Delete a deal", Group: "transactions"},
	{Command: "transactions get", Description: "Get deal by ID", Group: "transactions"},
	{Command: "transactions list", Description: "Returns deals ordered by health. Supports search (?q=), status filter, health filter, and closing date range.", Group: "transactions"},
	{Command: "transactions preview-csv-import", Description: "Parses uploaded CSV content and returns auto-mapped columns against canonical field keys. Unmapped columns are flagged for manual review.", Group: "transactions"},
	{Command: "transactions update", Description: "Status changes are validated against the deal state machine. Invalid transitions return 422.", Group: "transactions"},
	{Command: "transactions contacts link-to-transaction", Description: "Pass `contactId` to link an existing contact, or pass `firstName` + `lastName` (with optional emails/phones) to create and link in one atomic call.", Group: "transactions"},
	{Command: "transactions contacts list-transaction", Description: "List contacts for a deal", Group: "transactions"},
	{Command: "transactions documents link", Description: "Link an already-uploaded S3 object to a deal", Group: "transactions"},
	{Command: "transactions documents list", Description: "List documents for a deal", Group: "transactions"},
	{Command: "transactions documents upload", Description: "Accepts multipart PDF upload. Stores in S3/R2 with a deal-scoped path.", Group: "transactions"},
	{Command: "transactions email-filter confirm-transaction-installation", Description: "Confirm Gmail filter installation for a deal", Group: "transactions"},
	{Command: "transactions email-filter get-transaction", Description: "Returns a Gmail-importable filter XML that matches emails from deal contacts and auto-forwards to the deal's capture address. When no contacts have email addresses, returns JSON with help text instead.", Group: "transactions"},
	{Command: "transactions events create-activity", Description: "Record an activity event", Group: "transactions"},
	{Command: "transactions events list-transaction", Description: "Returns activity events paginated, newest first. Supports filtering by event_type and actor_type.", Group: "transactions"},
	{Command: "transactions events stream-transaction", Description: "Server-Sent Events stream. Supports Last-Event-ID for reconnect replay. If Last-Event-ID references a deleted/unknown event, sends a 'resync' event then replays last 50.", Group: "transactions"},
	{Command: "transactions fields batch-write", Description: "Atomically writes all extracted values with idempotency key.", Group: "transactions"},
	{Command: "transactions fields list-values", Description: "List all field values with provenance", Group: "transactions"},
	{Command: "transactions fields mark-disputed", Description: "Mark a field as disputed (conflicting values)", Group: "transactions"},
	{Command: "transactions fields mark-reviewed", Description: "Mark a field as reviewed by TC", Group: "transactions"},
	{Command: "transactions fields mark-stale", Description: "Mark a field as stale (may be outdated)", Group: "transactions"},
	{Command: "transactions fields review-summary", Description: "Returns count of fields in each review state for the overview tab.", Group: "transactions"},
	{Command: "transactions fields set-value", Description: "Triggers provenance storage and DateRule recalculation for dependent tasks.", Group: "transactions"},
	{Command: "transactions portal create-invite", Description: "Creates a magic link scoped to a deal and role. Re-sending invalidates previous links for the same contact.", Group: "transactions"},
	{Command: "transactions portal list-documents", Description: "Returns documents filtered by the authenticated portal user's role. Requires portal session token.", Group: "transactions"},
	{Command: "transactions portal revoke-invite", Description: "Revoke a portal invite", Group: "transactions"},
	{Command: "transactions tasks create", Description: "Create a task", Group: "transactions"},
	{Command: "transactions tasks list", Description: "List tasks for a deal", Group: "transactions"},
	{Command: "webhooks create-subscription", Description: "Create a webhook subscription", Group: "webhooks"},
	{Command: "webhooks delete-subscription", Description: "Delete a webhook subscription", Group: "webhooks"},
	{Command: "webhooks handle-inbound-email", Description: "Receives inbound emails, associates with transaction via reply address, stores as received email.", Group: "webhooks"},
	{Command: "webhooks list-deliveries", Description: "List delivery attempts for a webhook subscription", Group: "webhooks"},
	{Command: "webhooks list-subscriptions", Description: "List webhook subscriptions for the signed-in TC", Group: "webhooks"},
	{Command: "webhooks update-subscription", Description: "Update a webhook subscription", Group: "webhooks"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  theclose-pp-cli which "stale tickets"
  theclose-pp-cli which "bottleneck"
  theclose-pp-cli which --limit 1 "send message"
  theclose-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
