version: 2
project_name: intervals-icu-pp-cli
changelog:
  disable: true
builds:
  - id: intervals-icu-pp-cli
    main: ./cmd/intervals-icu-pp-cli
    binary: intervals-icu-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/other/intervals-icu/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: intervals-icu-pp-mcp
    main: ./cmd/intervals-icu-pp-mcp
    binary: intervals-icu-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: intervals-icu-pp-cli
    repository:
      owner: milosm
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "The first intervals."
    install: |
      bin.install "intervals-icu-pp-cli"
      bin.install "intervals-icu-pp-mcp"
