// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	"path/filepath"
	"sync"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// TestSchemaVersion_StampedOnFreshDB verifies that opening a brand-new
// database stamps the current schema version. This is the contract that
// makes StoreSchemaVersion upgrades safe: every freshly-created DB
// records the version it was built under.
func TestSchemaVersion_StampedOnFreshDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open fresh db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("fresh db version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_StampExistingZeroDB verifies the stamp-and-continue
// rule for existing deployed databases. A DB that predates the gate has
// user_version = 0; opening it with this binary should stamp the version
// to StoreSchemaVersion without touching any data.
func TestSchemaVersion_StampExistingZeroDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with user_version = 0 and no tables, simulating
	// a database created by a pre-gate version of the binary before any
	// migrations ran.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 0`); err != nil {
		t.Fatalf("stamp zero: %v", err)
	}
	raw.Close()

	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open pre-gate db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("post-stamp version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_RefusesNewerDB verifies fail-fast when the on-disk
// schema is newer than the binary supports. Without this gate, a user
// who upgrades their library but not their binary would hit silent
// "no such column" errors instead of a clear version mismatch.
func TestSchemaVersion_RefusesNewerDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	_, err = Open(dbPath)
	if err == nil {
		t.Fatalf("expected open to fail on newer schema, got nil")
	}
}

// TestMigrate_ConcurrentFreshDB exercises the BEGIN IMMEDIATE migration
// transaction. Without it, N goroutines opening the same fresh DB in
// parallel race per CREATE TABLE statement and trip SQLITE_BUSY despite
// the busy_timeout. With it, they serialize on the RESERVED lock
// acquired at BEGIN time and every Open succeeds.
func TestMigrate_ConcurrentFreshDB(t *testing.T) {
	if testing.Short() {
		t.Skip("concurrent migration test can take up to migrationLockTimeout under contention")
	}
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	const n = 8
	errs := make(chan error, n)
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			s, err := Open(dbPath)
			if err != nil {
				errs <- err
				return
			}
			s.Close()
		}()
	}
	wg.Wait()
	close(errs)

	for err := range errs {
		t.Fatalf("concurrent Open failed: %v", err)
	}
}

// holdWriteLock takes an exclusive write lock on dbPath that a peer's
// BEGIN IMMEDIATE cannot acquire until the returned cleanup runs. Used
// to construct contention scenarios in the migration tests.
func holdWriteLock(t *testing.T, dbPath string) (cleanup func()) {
	t.Helper()
	holder, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		t.Fatalf("open holder: %v", err)
	}
	htx, err := holder.Begin()
	if err != nil {
		_ = holder.Close()
		t.Fatalf("begin holder tx: %v", err)
	}
	if _, err := htx.Exec(`CREATE TABLE IF NOT EXISTS holder_lock (id INTEGER)`); err != nil {
		_ = htx.Rollback()
		_ = holder.Close()
		t.Fatalf("seed holder write: %v", err)
	}
	return func() {
		_ = htx.Rollback()
		_ = holder.Close()
	}
}

// TestOpenWithContext_RespectsCancellation verifies that a caller that
// cancels its context during a stalled migration sees the cancellation
// surface as the returned error within a short window, instead of
// having to wait out the full migrationLockTimeout. SIGINT in a Cobra
// command's context must interrupt store.Open, not just block on it.
func TestOpenWithContext_RespectsCancellation(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")
	defer holdWriteLock(t, dbPath)()

	// Pre-cancel the context. The migration's BEGIN IMMEDIATE will BUSY
	// against the holder; the very first iteration of retryOnBusy then
	// hits the ctx.Done() arm of its select and propagates ctx.Canceled.
	// A blocked-then-cancel pattern using time.Sleep would prove the
	// same property but cost the sleep interval on every CI run.
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	start := time.Now()
	_, err := OpenWithContext(ctx, dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected OpenWithContext to fail under contention with cancelled ctx")
	}
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("expected context.Canceled in error chain, got: %v", err)
	}
	// Without ctx threading this would block until migrationLockTimeout
	// (default 30s). 5s is generous headroom over the actual return
	// time (microseconds for a pre-cancelled ctx) without flaking CI.
	if elapsed > 5*time.Second {
		t.Fatalf("OpenWithContext returned after %s; pre-cancelled ctx should short-circuit immediately", elapsed)
	}
}

// TestMigrate_RejectsNewerDBImmediately verifies that an old binary
// opening a newer-schema DB rejects fast even when a peer migrator is
// still holding the write lock. The schema-version check runs on the
// pinned connection BEFORE BEGIN IMMEDIATE so the rejection path
// doesn't have to wait out the migration lock.
func TestMigrate_RejectsNewerDBImmediately(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-stamp the DB at a version this binary doesn't support.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	defer holdWriteLock(t, dbPath)()

	start := time.Now()
	_, err = Open(dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected Open to refuse a newer-schema DB")
	}
	// The fast-path goal: rejection must arrive well under
	// migrationLockTimeout. 5s leaves headroom over the WAL init race
	// (a few ms in practice) without being so tight CI flakes.
	if elapsed > 5*time.Second {
		t.Fatalf("Open rejected after %s; fast-path should reject in well under migrationLockTimeout (30s)", elapsed)
	}
}

// TestSchemaVersion_ReopenIsIdempotent verifies that opening an already
// correctly-stamped DB is a no-op — the second open reads the version
// and the migrations are all idempotent (CREATE TABLE IF NOT EXISTS).
func TestSchemaVersion_ReopenIsIdempotent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	s1, err := Open(dbPath)
	if err != nil {
		t.Fatalf("first open: %v", err)
	}
	s1.Close()

	s2, err := Open(dbPath)
	if err != nil {
		t.Fatalf("second open: %v", err)
	}
	defer s2.Close()

	v, err := s2.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("reopened version = %d, want %d", v, StoreSchemaVersion)
	}
}

func TestResources_CompositeKeyPreservesOverlappingIDs(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer s.Close()

	if err := s.Upsert("biz", "shared", []byte(`{"kind":"biz","name":"Pinky restaurant"}`)); err != nil {
		t.Fatalf("upsert biz: %v", err)
	}
	if err := s.Upsert("bookmark", "shared", []byte(`{"kind":"bookmark","note":"anniversary"}`)); err != nil {
		t.Fatalf("upsert bookmark: %v", err)
	}

	biz, err := s.Get("biz", "shared")
	if err != nil {
		t.Fatalf("get biz: %v", err)
	}
	if string(biz) != `{"kind":"biz","name":"Pinky restaurant"}` {
		t.Fatalf("biz payload = %s", biz)
	}

	bookmark, err := s.Get("bookmark", "shared")
	if err != nil {
		t.Fatalf("get bookmark: %v", err)
	}
	if string(bookmark) != `{"kind":"bookmark","note":"anniversary"}` {
		t.Fatalf("bookmark payload = %s", bookmark)
	}

	var count int
	if err := s.DB().QueryRow(`SELECT COUNT(*) FROM resources WHERE id = 'shared'`).Scan(&count); err != nil {
		t.Fatalf("count overlapping rows: %v", err)
	}
	if count != 2 {
		t.Fatalf("overlapping row count = %d, want 2", count)
	}

	matches, err := s.Search("restaurant", 10)
	if err != nil {
		t.Fatalf("search restaurant: %v", err)
	}
	if len(matches) != 1 || string(matches[0]) != `{"kind":"biz","name":"Pinky restaurant"}` {
		t.Fatalf("restaurant search = %q, want only biz payload", matches)
	}
}

// Callers detect missing rows via errors.Is(err, sql.ErrNoRows); present
// rows return the JSON payload with a nil error.
func TestGet_MissingRowReturnsErrNoRows(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	data, err := s.Get("missing_type", "missing_id")
	if !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("Get missing row err = %v, want sql.ErrNoRows", err)
	}
	if data != nil {
		t.Fatalf("Get missing row data = %s, want nil", data)
	}

	if err := s.Upsert("present_type", "present_id", []byte(`{"ok":true}`)); err != nil {
		t.Fatalf("upsert: %v", err)
	}
	got, err := s.Get("present_type", "present_id")
	if err != nil {
		t.Fatalf("Get present row: %v", err)
	}
	if string(got) != `{"ok":true}` {
		t.Fatalf("Get present row data = %s, want {\"ok\":true}", got)
	}
}

func TestMigrate_ResourcesCompositeKeyUpgrade(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE resources (
		id TEXT PRIMARY KEY,
		resource_type TEXT NOT NULL,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create v1 resources: %v", err)
	}
	if _, err := raw.Exec(`CREATE VIRTUAL TABLE resources_fts USING fts5(
		id, resource_type, content, tokenize='porter unicode61'
	)`); err != nil {
		raw.Close()
		t.Fatalf("create v1 resources_fts: %v", err)
	}
	if _, err := raw.Exec(`INSERT INTO resources (id, resource_type, data) VALUES ('shared', 'biz', '{"kind":"biz","name":"legacy restaurant"}')`); err != nil {
		raw.Close()
		t.Fatalf("insert v1 resource: %v", err)
	}
	if _, err := raw.Exec(`INSERT INTO resources_fts (rowid, id, resource_type, content) VALUES (1, 'shared', 'biz', '{"kind":"biz","name":"legacy restaurant"}')`); err != nil {
		raw.Close()
		t.Fatalf("insert v1 fts row: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 1`); err != nil {
		raw.Close()
		t.Fatalf("stamp v1: %v", err)
	}
	raw.Close()

	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("upgraded version = %d, want %d", v, StoreSchemaVersion)
	}

	rows, err := s.DB().Query(`PRAGMA table_info(resources)`)
	if err != nil {
		t.Fatalf("table_info resources: %v", err)
	}
	defer rows.Close()

	pk := map[string]int{}
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pkOrder int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pkOrder); err != nil {
			t.Fatalf("scan table_info: %v", err)
		}
		pk[name] = pkOrder
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("table_info rows: %v", err)
	}
	if pk["resource_type"] != 1 || pk["id"] != 2 {
		t.Fatalf("resources primary key order = resource_type:%d id:%d, want resource_type:1 id:2", pk["resource_type"], pk["id"])
	}

	if err := s.Upsert("bookmark", "shared", []byte(`{"kind":"bookmark","note":"after upgrade"}`)); err != nil {
		t.Fatalf("upsert overlapping resource after upgrade: %v", err)
	}

	biz, err := s.Get("biz", "shared")
	if err != nil {
		t.Fatalf("get migrated biz: %v", err)
	}
	if string(biz) != `{"kind":"biz","name":"legacy restaurant"}` {
		t.Fatalf("migrated biz payload = %s", biz)
	}

	bookmark, err := s.Get("bookmark", "shared")
	if err != nil {
		t.Fatalf("get upgraded bookmark: %v", err)
	}
	if string(bookmark) != `{"kind":"bookmark","note":"after upgrade"}` {
		t.Fatalf("upgraded bookmark payload = %s", bookmark)
	}

	matches, err := s.Search("legacy", 10)
	if err != nil {
		t.Fatalf("search migrated fts: %v", err)
	}
	if len(matches) != 1 || string(matches[0]) != `{"kind":"biz","name":"legacy restaurant"}` {
		t.Fatalf("legacy search = %q, want migrated biz payload", matches)
	}
}

// TestOpenReadOnly_RejectsWrites pins the contract: direct and CTE-wrapped
// writes against the main DB fail under mode=ro. Deliberately does not
// assert VACUUM INTO and ATTACH DATABASE — modernc.org/sqlite allows both
// under mode=ro, so those defenses live in the handleSQL keyword blocklist.
func TestOpenReadOnly_RejectsWrites(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	rw, err := Open(dbPath)
	if err != nil {
		t.Fatalf("seed open: %v", err)
	}
	if _, err := rw.DB().Exec(`INSERT INTO resources (id, resource_type, data) VALUES ('seed', 'thing', '{}')`); err != nil {
		t.Fatalf("seed insert: %v", err)
	}
	rw.Close()

	ro, err := OpenReadOnly(dbPath)
	if err != nil {
		t.Fatalf("open read-only: %v", err)
	}
	defer ro.Close()

	writes := []struct {
		name string
		stmt string
	}{
		{"insert", `INSERT INTO resources (id, resource_type, data) VALUES ('x', 'y', '{}')`},
		{"update", `UPDATE resources SET resource_type = 'hijacked' WHERE id = 'seed'`},
		{"delete", `DELETE FROM resources WHERE id = 'seed'`},
		{"replace", `REPLACE INTO resources (id, resource_type, data) VALUES ('seed', 'evil', '{}')`},
		// CTE-wrapped INSERT is load-bearing: it justifies leaving WITH
		// out of the handleSQL blocklist so SELECT-form CTEs work.
		{"cte_insert", `WITH stale AS (SELECT id FROM resources) INSERT INTO resources (id, resource_type, data) SELECT id || '-evil', 'thing', '{}' FROM stale`},
	}
	for _, w := range writes {
		if _, err := ro.DB().Exec(w.stmt); err == nil {
			t.Errorf("%s succeeded under mode=ro; expected rejection. stmt=%q", w.name, w.stmt)
		}
	}

	var count int
	if err := ro.DB().QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&count); err != nil {
		t.Fatalf("read-only SELECT failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("SELECT returned %d rows, want 1 (only the seed should remain)", count)
	}
	if err := ro.DB().QueryRow(`WITH r AS (SELECT id FROM resources WHERE id = 'seed') SELECT COUNT(*) FROM r`).Scan(&count); err != nil {
		t.Fatalf("read-only WITH...SELECT CTE failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("CTE SELECT returned %d rows, want 1", count)
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Address verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Address(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "address" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("address")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"city",
		"label",
		"state",
		"street",
		"unit",
		"zip",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from address after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Admin verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Admin(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "admin" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("admin")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"accuracy_rate",
		"corrections",
		"field_key",
		"most_recent_correction",
		"total_extractions",
		"prompt_version",
		"confidence",
		"corrected_at",
		"corrected_by",
		"corrected_value",
		"model",
		"original_ai_value",
		"source_document_id",
		"transaction_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from admin after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_AgentActions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_AgentActions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "agent_actions" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("agent_actions")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"approved_at",
		"approved_by_id",
		"created_at",
		"idempotency_key",
		"reasoning",
		"resume_token",
		"source_document_id",
		"source_page",
		"source_quote",
		"stale_reason",
		"status",
		"transaction_id",
		"type",
		"version",
		"workflow_run_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from agent_actions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_AcceptContactSuggestion verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_AcceptContactSuggestion(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "accept_contact_suggestion" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("accept_contact_suggestion")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_actions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from accept_contact_suggestion after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Approve verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Approve(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "approve" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("approve")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_actions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from approve after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DismissContactSuggestion verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DismissContactSuggestion(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "dismiss_contact_suggestion" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("dismiss_contact_suggestion")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_actions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from dismiss_contact_suggestion after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_MarkStale verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_MarkStale(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "mark_stale" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("mark_stale")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_actions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from mark_stale after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Reject verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Reject(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "reject" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("reject")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_actions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from reject after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_AgentTokens verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_AgentTokens(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "agent_tokens" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("agent_tokens")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"expires_at",
		"last_used_at",
		"name",
		"permission",
		"revoked_at",
		"rotated_from_id",
		"scope",
		"scope_resource_id",
		"token_prefix",
		"updated_at",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from agent_tokens after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Revoke verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Revoke(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "revoke" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("revoke")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_tokens_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from revoke after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Usages verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Usages(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "usages" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("usages")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_tokens_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from usages after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Callouts verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Callouts(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "callouts" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("callouts")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"callout_key",
		"seen_at",
		"user_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from callouts after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Contacts verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Contacts(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "contacts" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("contacts")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_license_number",
		"anniversary",
		"birthday",
		"created_at",
		"created_by",
		"fax",
		"first_name",
		"last_name",
		"lead_source",
		"nick_name",
		"prefix",
		"suffix",
		"updated_at",
		"website",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from contacts after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Download verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Download(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "download" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("download")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"documents_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from download after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Status verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Status(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "status" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("status")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"documents_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from status after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Versions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Versions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "versions" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("versions")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"documents_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from versions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Events verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Events(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "events" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("events")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"actor_id",
		"actor_type",
		"timestamp",
		"transaction_id",
		"type",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from events after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Submit verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Submit(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "submit" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("submit")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"forms_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from submit after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Cancel verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Cancel(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "cancel" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("cancel")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"intake_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from cancel after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Commit verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Commit(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "commit" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("commit")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"intake_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from commit after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Notifications verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Notifications(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "notifications" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("notifications")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"body",
		"created_at",
		"link_to",
		"read_at",
		"tc_id",
		"title",
		"type",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from notifications after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Read verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Read(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "read" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("read")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"notifications_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from read after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Schema verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Schema(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "schema" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("schema")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"agent_description",
		"group",
		"key",
		"label",
		"merge_key",
		"portal_visible",
		"required",
		"section",
		"type",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from schema after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Tasks verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Tasks(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "tasks" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("tasks")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"assignee_contact_id",
		"assignee_id",
		"assignee_tc_id",
		"assignee_type",
		"claimed_at",
		"claimed_by",
		"created_at",
		"description",
		"due_date",
		"portal_visible",
		"slug",
		"source_catalog_id",
		"source_catalog_version",
		"status",
		"title",
		"transaction_id",
		"updated_at",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from tasks after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Templates verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Templates(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "templates" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("templates")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"built_in",
		"created_at",
		"created_by",
		"description",
		"name",
		"type",
		"updated_at",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from templates after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Apply verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Apply(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "apply" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("apply")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"templates_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from apply after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Transactions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Transactions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"created_by",
		"health",
		"inbound_email_address",
		"status",
		"team_id",
		"type",
		"updated_at",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_CapturedEmails verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_CapturedEmails(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "captured_emails" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("captured_emails")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from captured_emails after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsContacts verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsContacts(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_contacts" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_contacts")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_contacts after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsDocuments verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsDocuments(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_documents" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_documents")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_documents after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_EmailFilter verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_EmailFilter(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "email_filter" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("email_filter")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from email_filter after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsEmails verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsEmails(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_emails" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_emails")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_emails after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsEvents verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsEvents(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_events" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_events")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_events after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Fields verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Fields(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "fields" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("fields")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from fields after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsPortal verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsPortal(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_portal" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_portal")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_portal after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_TransactionsTasks verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_TransactionsTasks(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "transactions_tasks" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("transactions_tasks")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"transactions_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from transactions_tasks after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Webhooks verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Webhooks(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "webhooks" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("webhooks")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"attempt",
		"delivered_at",
		"error",
		"event_type",
		"max_attempts",
		"status_code",
		"subscription_id",
		"success",
		"created_at",
		"enabled",
		"updated_at",
		"url",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from webhooks after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_SyncState verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_SyncState(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "sync_state" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("sync_state")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"last_cursor",
		"last_synced_at",
		"total_count",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from sync_state after migrate", want)
		}
	}
}
