// Copyright 2026 cathrynlavery. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "name", "uuid", "slug", "key", "code", "uid"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesAddressTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed address table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAddressTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("address", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "address").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "address")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count address: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("address count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAdminTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed admin table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAdminTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("admin", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "admin").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "admin")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count admin: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("admin count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAgentActionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed agent_actions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAgentActionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("agent-actions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "agent-actions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "agent_actions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count agent_actions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("agent_actions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAcceptContactSuggestionTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed accept_contact_suggestion table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAcceptContactSuggestionTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_actions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("accept_contact_suggestion", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "accept_contact_suggestion").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "accept_contact_suggestion")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count accept_contact_suggestion: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("accept_contact_suggestion count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesApproveTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed approve table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesApproveTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_actions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("approve", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "approve").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "approve")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count approve: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("approve count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesDismissContactSuggestionTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed dismiss_contact_suggestion table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDismissContactSuggestionTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_actions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("dismiss_contact_suggestion", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "dismiss_contact_suggestion").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "dismiss_contact_suggestion")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count dismiss_contact_suggestion: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("dismiss_contact_suggestion count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesMarkStaleTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed mark_stale table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMarkStaleTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_actions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("mark_stale", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "mark_stale").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "mark_stale")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count mark_stale: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("mark_stale count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesRejectTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed reject table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesRejectTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_actions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_actions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("reject", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "reject").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "reject")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count reject: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("reject count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAgentTokensTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed agent_tokens table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAgentTokensTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("agent-tokens", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "agent-tokens").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "agent_tokens")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count agent_tokens: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("agent_tokens count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesRevokeTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed revoke table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesRevokeTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_tokens_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_tokens_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_tokens_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("revoke", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "revoke").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "revoke")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count revoke: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("revoke count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesUsagesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed usages table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesUsagesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "agent_tokens_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "agent_tokens_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "agent_tokens_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("usages", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "usages").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "usages")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count usages: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("usages count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsUsagesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsUsagesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("usages", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "usages")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesCalloutsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed callouts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCalloutsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("callouts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "callouts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "callouts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count callouts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("callouts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesContactsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed contacts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesContactsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("contacts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "contacts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "contacts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count contacts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("contacts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesDownloadTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed download table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDownloadTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "documents_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("download", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "download").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "download")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count download: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("download count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesStatusTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed status table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesStatusTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "documents_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("status", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "status").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "status")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count status: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("status count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesVersionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed versions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesVersionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "documents_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "documents_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("versions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "versions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "versions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count versions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("versions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEventsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed events table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEventsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("events", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "events").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "events")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count events: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("events count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSubmitTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed submit table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSubmitTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "forms_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "forms_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "forms_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("submit", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "submit").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "submit")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count submit: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("submit count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesCancelTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed cancel table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCancelTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "intake_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "intake_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "intake_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("cancel", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "cancel").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "cancel")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count cancel: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("cancel count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesCommitTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed commit table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCommitTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "intake_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "intake_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "intake_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("commit", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "commit").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "commit")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count commit: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("commit count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesNotificationsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed notifications table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesNotificationsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("notifications", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "notifications").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "notifications")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count notifications: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("notifications count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesReadTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed read table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesReadTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "notifications_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "notifications_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "notifications_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("read", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "read").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "read")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count read: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("read count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSchemaTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed schema table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSchemaTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("schema", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "schema").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "schema")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count schema: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("schema count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTasksTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tasks table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTasksTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("tasks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tasks").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tasks")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tasks: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tasks count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTemplatesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed templates table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTemplatesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("templates", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "templates").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "templates")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count templates: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("templates count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesApplyTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed apply table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesApplyTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "templates_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "templates_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "templates_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("apply", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "apply").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "apply")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count apply: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("apply count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("transactions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesCapturedEmailsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed captured_emails table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCapturedEmailsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("captured_emails", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "captured_emails").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "captured_emails")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count captured_emails: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("captured_emails count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsContactsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_contacts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsContactsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_contacts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_contacts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_contacts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_contacts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_contacts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsDocumentsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_documents table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsDocumentsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_documents", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_documents").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_documents")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_documents: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_documents count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEmailFilterTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed email_filter table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEmailFilterTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("email_filter", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "email_filter").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "email_filter")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count email_filter: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("email_filter count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsEmailsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_emails table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsEmailsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_emails", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_emails").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_emails")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_emails: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_emails count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsEventsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_events table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsEventsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_events", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_events").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_events")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_events: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_events count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsTransactionsEventsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsTransactionsEventsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_events", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "transactions_events")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesFieldsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed fields table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesFieldsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("fields", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "fields").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "fields")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count fields: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("fields count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsPortalTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_portal table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsPortalTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_portal", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_portal").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_portal")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_portal: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_portal count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTransactionsTasksTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed transactions_tasks table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTransactionsTasksTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "transactions_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "transactions_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("transactions_tasks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "transactions_tasks").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "transactions_tasks")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count transactions_tasks: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("transactions_tasks count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesWebhooksTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed webhooks table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesWebhooksTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("webhooks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "webhooks").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "webhooks")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count webhooks: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("webhooks count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}
